"""add_audit_trail_fields

Revision ID: 02ff315a3abc
Revises: da35eb55a74d
Create Date: 2026-03-31 14:34:56.387033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ff315a3abc'
down_revision: Union[str, None] = 'da35eb55a74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('created_by', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('sent_by', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('voided_by', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('written_off_by', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('written_off_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('converted_by', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('recorded_by', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'recorded_by')
    op.drop_column('invoices', 'converted_at')
    op.drop_column('invoices', 'converted_by')
    op.drop_column('invoices', 'written_off_at')
    op.drop_column('invoices', 'written_off_by')
    op.drop_column('invoices', 'voided_at')
    op.drop_column('invoices', 'voided_by')
    op.drop_column('invoices', 'sent_by')
    op.drop_column('invoices', 'created_by')
    # ### end Alembic commands ###
