"""Add assigned_to on agent_threads

Revision ID: 057dc809476f
Revises: 885a91bafc3d
Create Date: 2026-03-25 06:42:00.796743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057dc809476f'
down_revision: Union[str, None] = '885a91bafc3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_threads', sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True))
    op.add_column('agent_threads', sa.Column('assigned_to_name', sa.String(length=100), nullable=True))
    op.add_column('agent_threads', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'agent_threads', 'users', ['assigned_to_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_threads', type_='foreignkey')
    op.drop_column('agent_threads', 'assigned_at')
    op.drop_column('agent_threads', 'assigned_to_name')
    op.drop_column('agent_threads', 'assigned_to_user_id')
    # ### end Alembic commands ###
