"""make agent_message_id nullable, add customer fields to actions

Revision ID: 0ae300282baf
Revises: 8bcd24007935
Create Date: 2026-03-23 20:52:51.623700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae300282baf'
down_revision: Union[str, None] = '8bcd24007935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_actions', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('agent_actions', sa.Column('property_address', sa.String(length=300), nullable=True))
    op.alter_column('agent_actions', 'agent_message_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_actions', 'agent_message_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('agent_actions', 'property_address')
    op.drop_column('agent_actions', 'customer_name')
    # ### end Alembic commands ###
