"""add missing fields to emd_inspections, emd_equipment, emd_violations

Revision ID: 1323a5b482cb
Revises: a1233ba2e7d0
Create Date: 2026-03-19 06:31:24.055078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1323a5b482cb'
down_revision: Union[str, None] = 'a1233ba2e7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emd_equipment', sa.Column('rp_make', sa.String(length=100), nullable=True))
    op.add_column('emd_equipment', sa.Column('rp_model', sa.String(length=100), nullable=True))
    op.add_column('emd_equipment', sa.Column('rp_hp', sa.String(length=50), nullable=True))
    op.add_column('emd_equipment', sa.Column('bp_make', sa.String(length=100), nullable=True))
    op.add_column('emd_equipment', sa.Column('bp_model', sa.String(length=100), nullable=True))
    op.add_column('emd_equipment', sa.Column('bp_hp', sa.String(length=50), nullable=True))
    op.add_column('emd_equipment', sa.Column('filter_cleaning_method', sa.String(length=100), nullable=True))
    op.add_column('emd_equipment', sa.Column('df_type', sa.String(length=50), nullable=True))
    op.add_column('emd_equipment', sa.Column('df_make', sa.String(length=100), nullable=True))
    op.add_column('emd_equipment', sa.Column('main_drain_capacity_gpm', sa.Integer(), nullable=True))
    op.add_column('emd_equipment', sa.Column('main_drain_config', sa.String(length=50), nullable=True))
    op.add_column('emd_equipment', sa.Column('equalizer_capacity_gpm', sa.Integer(), nullable=True))
    op.add_column('emd_equipment', sa.Column('skimmer_count', sa.Integer(), nullable=True))
    op.add_column('emd_equipment', sa.Column('equipment_matches_emd', sa.Boolean(), nullable=True))
    op.add_column('emd_equipment', sa.Column('equipment_text', sa.Text(), nullable=True))
    op.add_column('emd_inspections', sa.Column('co_inspector', sa.String(length=100), nullable=True))
    op.add_column('emd_inspections', sa.Column('inspector_phone', sa.String(length=50), nullable=True))
    op.add_column('emd_inspections', sa.Column('pool_spa_temp', sa.Integer(), nullable=True))
    op.add_column('emd_inspections', sa.Column('rp_gauge', sa.Integer(), nullable=True))
    op.add_column('emd_inspections', sa.Column('rv_gauge', sa.Integer(), nullable=True))
    op.add_column('emd_inspections', sa.Column('bp_gauge', sa.Integer(), nullable=True))
    op.add_column('emd_inspections', sa.Column('bv_gauge', sa.Integer(), nullable=True))
    op.add_column('emd_inspections', sa.Column('uv_output', sa.String(length=50), nullable=True))
    op.add_column('emd_inspections', sa.Column('accepted_by', sa.String(length=200), nullable=True))
    op.add_column('emd_inspections', sa.Column('reviewed_by', sa.String(length=200), nullable=True))
    op.add_column('emd_violations', sa.Column('code_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emd_violations', 'code_description')
    op.drop_column('emd_inspections', 'reviewed_by')
    op.drop_column('emd_inspections', 'accepted_by')
    op.drop_column('emd_inspections', 'uv_output')
    op.drop_column('emd_inspections', 'bv_gauge')
    op.drop_column('emd_inspections', 'bp_gauge')
    op.drop_column('emd_inspections', 'rv_gauge')
    op.drop_column('emd_inspections', 'rp_gauge')
    op.drop_column('emd_inspections', 'pool_spa_temp')
    op.drop_column('emd_inspections', 'inspector_phone')
    op.drop_column('emd_inspections', 'co_inspector')
    op.drop_column('emd_equipment', 'equipment_text')
    op.drop_column('emd_equipment', 'equipment_matches_emd')
    op.drop_column('emd_equipment', 'skimmer_count')
    op.drop_column('emd_equipment', 'equalizer_capacity_gpm')
    op.drop_column('emd_equipment', 'main_drain_config')
    op.drop_column('emd_equipment', 'main_drain_capacity_gpm')
    op.drop_column('emd_equipment', 'df_make')
    op.drop_column('emd_equipment', 'df_type')
    op.drop_column('emd_equipment', 'filter_cleaning_method')
    op.drop_column('emd_equipment', 'bp_hp')
    op.drop_column('emd_equipment', 'bp_model')
    op.drop_column('emd_equipment', 'bp_make')
    op.drop_column('emd_equipment', 'rp_hp')
    op.drop_column('emd_equipment', 'rp_model')
    op.drop_column('emd_equipment', 'rp_make')
    # ### end Alembic commands ###
