"""phase2_routing_tables

Revision ID: 14a646f36141
Revises: 3d3a1af61a79
Create Date: 2026-01-31 12:14:30.904259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a646f36141'
down_revision: Union[str, None] = '3d3a1af61a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('tech_id', sa.String(length=36), nullable=False),
    sa.Column('service_day', sa.String(length=20), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_distance_miles', sa.Float(), nullable=False),
    sa.Column('total_stops', sa.Integer(), nullable=False),
    sa.Column('optimization_algorithm', sa.String(length=50), nullable=True),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_id'], ['techs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_organization_id'), 'routes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_routes_service_day'), 'routes', ['service_day'], unique=False)
    op.create_index(op.f('ix_routes_tech_id'), 'routes', ['tech_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival_time', sa.Time(), nullable=True),
    sa.Column('estimated_service_duration', sa.Integer(), nullable=False),
    sa.Column('estimated_drive_time_from_previous', sa.Integer(), nullable=False),
    sa.Column('estimated_distance_from_previous', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_table('temp_tech_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('temp_tech_id', sa.String(length=36), nullable=False),
    sa.Column('temp_service_day', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temp_tech_id'], ['techs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'property_id', name='uq_temp_assignment_org_property')
    )
    op.create_index(op.f('ix_temp_tech_assignments_organization_id'), 'temp_tech_assignments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_tech_assignments_organization_id'), table_name='temp_tech_assignments')
    op.drop_table('temp_tech_assignments')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_routes_tech_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_service_day'), table_name='routes')
    op.drop_index(op.f('ix_routes_organization_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
