"""add agent_corrections table

Revision ID: 163990138c45
Revises: b101b746291e
Create Date: 2026-03-30 19:58:09.777111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163990138c45'
down_revision: Union[str, None] = 'b101b746291e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('correction_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('input_context', sa.Text(), nullable=True),
    sa.Column('original_output', sa.Text(), nullable=True),
    sa.Column('corrected_output', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_corrections_agent_type'), 'agent_corrections', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_corrections_category'), 'agent_corrections', ['category'], unique=False)
    op.create_index(op.f('ix_agent_corrections_customer_id'), 'agent_corrections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_agent_corrections_organization_id'), 'agent_corrections', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_corrections_organization_id'), table_name='agent_corrections')
    op.drop_index(op.f('ix_agent_corrections_customer_id'), table_name='agent_corrections')
    op.drop_index(op.f('ix_agent_corrections_category'), table_name='agent_corrections')
    op.drop_index(op.f('ix_agent_corrections_agent_type'), table_name='agent_corrections')
    op.drop_table('agent_corrections')
    # ### end Alembic commands ###
