"""add monthly_rate to properties

Revision ID: 18590e8b961d
Revises: 587b8e26a186
Create Date: 2026-03-22 07:54:03.902518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18590e8b961d'
down_revision: Union[str, None] = '587b8e26a186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('properties', sa.Column('monthly_rate', sa.Float(), nullable=True))
    # Backfill: set property rate to sum of its active BOW rates
    op.execute("""
        UPDATE properties p
        SET monthly_rate = (
            SELECT COALESCE(SUM(b.monthly_rate), 0)
            FROM bodies_of_water b
            WHERE b.property_id = p.id AND b.is_active = true
        )
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'monthly_rate')
    # ### end Alembic commands ###
