"""add program_identifier to emd_facilities and pdf_retry fields to emd_inspections

Revision ID: 19441f30fa8c
Revises: 237d147645e8
Create Date: 2026-03-18 04:05:14.126935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19441f30fa8c'
down_revision: Union[str, None] = '237d147645e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emd_facilities', sa.Column('program_identifier', sa.String(length=100), nullable=True))
    op.add_column('emd_inspections', sa.Column('pdf_download_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('emd_inspections', sa.Column('pdf_permanently_missing', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('emd_inspections', 'closure_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('emd_inspections', 'reinspection_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('properties', 'photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('emd_inspections', 'reinspection_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('emd_inspections', 'closure_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('emd_inspections', 'pdf_permanently_missing')
    op.drop_column('emd_inspections', 'pdf_download_attempts')
    op.drop_column('emd_facilities', 'program_identifier')
    # ### end Alembic commands ###
