"""add matched_customer_id and match_method to agent_messages

Revision ID: 2aa3322d2b81
Revises: 19ea293fd52b
Create Date: 2026-03-23 05:11:40.756324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa3322d2b81'
down_revision: Union[str, None] = '19ea293fd52b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_messages', sa.Column('matched_customer_id', sa.String(length=36), nullable=True))
    op.add_column('agent_messages', sa.Column('match_method', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_agent_messages_matched_customer_id'), 'agent_messages', ['matched_customer_id'], unique=False)
    op.create_foreign_key(None, 'agent_messages', 'customers', ['matched_customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_messages', type_='foreignkey')
    op.drop_index(op.f('ix_agent_messages_matched_customer_id'), table_name='agent_messages')
    op.drop_column('agent_messages', 'match_method')
    op.drop_column('agent_messages', 'matched_customer_id')
    # ### end Alembic commands ###
