"""add avg_drive_minutes, avg_drive_miles, visits_per_month to org_cost_settings

Revision ID: 2d880fca8c51
Revises: b5a4523c2def
Create Date: 2026-03-19 08:17:44.843854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d880fca8c51'
down_revision: Union[str, None] = 'b5a4523c2def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_cost_settings', sa.Column('avg_drive_minutes', sa.Float(), nullable=False, server_default='5.0'))
    op.add_column('org_cost_settings', sa.Column('avg_drive_miles', sa.Float(), nullable=False, server_default='2.0'))
    op.add_column('org_cost_settings', sa.Column('visits_per_month', sa.Float(), nullable=False, server_default='4.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_cost_settings', 'visits_per_month')
    op.drop_column('org_cost_settings', 'avg_drive_miles')
    op.drop_column('org_cost_settings', 'avg_drive_minutes')
    # ### end Alembic commands ###
