"""add EMD facility inspection violation equipment tables

Revision ID: 2f849d9d94e2
Revises: 188053029ea7
Create Date: 2026-03-16 17:10:16.710616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f849d9d94e2'
down_revision: Union[str, None] = '188053029ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emd_facilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('facility_id', sa.String(length=50), nullable=True),
    sa.Column('permit_holder', sa.String(length=255), nullable=True),
    sa.Column('facility_type', sa.String(length=50), nullable=True),
    sa.Column('matched_property_id', sa.String(length=36), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emd_facilities_facility_id'), 'emd_facilities', ['facility_id'], unique=True)
    op.create_index(op.f('ix_emd_facilities_matched_property_id'), 'emd_facilities', ['matched_property_id'], unique=False)
    op.create_index(op.f('ix_emd_facilities_organization_id'), 'emd_facilities', ['organization_id'], unique=False)
    op.create_table('emd_inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=50), nullable=True),
    sa.Column('inspection_date', sa.Date(), nullable=True),
    sa.Column('inspection_type', sa.String(length=50), nullable=True),
    sa.Column('inspector_name', sa.String(length=100), nullable=True),
    sa.Column('total_violations', sa.Integer(), nullable=False),
    sa.Column('major_violations', sa.Integer(), nullable=False),
    sa.Column('pool_capacity_gallons', sa.Integer(), nullable=True),
    sa.Column('flow_rate_gpm', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('report_notes', sa.Text(), nullable=True),
    sa.Column('closure_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['emd_facilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emd_inspections_facility_id'), 'emd_inspections', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emd_inspections_inspection_date'), 'emd_inspections', ['inspection_date'], unique=False)
    op.create_index(op.f('ix_emd_inspections_inspection_id'), 'emd_inspections', ['inspection_id'], unique=True)
    op.create_table('emd_equipment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('pool_capacity_gallons', sa.Integer(), nullable=True),
    sa.Column('flow_rate_gpm', sa.Integer(), nullable=True),
    sa.Column('filter_pump_1_make', sa.String(length=100), nullable=True),
    sa.Column('filter_pump_1_model', sa.String(length=100), nullable=True),
    sa.Column('filter_pump_1_hp', sa.String(length=50), nullable=True),
    sa.Column('filter_1_type', sa.String(length=50), nullable=True),
    sa.Column('filter_1_make', sa.String(length=100), nullable=True),
    sa.Column('filter_1_model', sa.String(length=100), nullable=True),
    sa.Column('sanitizer_1_type', sa.String(length=50), nullable=True),
    sa.Column('sanitizer_1_details', sa.String(length=200), nullable=True),
    sa.Column('main_drain_type', sa.String(length=100), nullable=True),
    sa.Column('main_drain_model', sa.String(length=100), nullable=True),
    sa.Column('main_drain_install_date', sa.String(length=50), nullable=True),
    sa.Column('equalizer_model', sa.String(length=100), nullable=True),
    sa.Column('equalizer_install_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['emd_facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['emd_inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emd_equipment_facility_id'), 'emd_equipment', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emd_equipment_inspection_id'), 'emd_equipment', ['inspection_id'], unique=False)
    op.create_table('emd_violations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('violation_code', sa.String(length=20), nullable=True),
    sa.Column('violation_title', sa.String(length=500), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('is_major_violation', sa.Boolean(), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=True),
    sa.Column('shorthand_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['emd_facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspection_id'], ['emd_inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emd_violations_facility_id'), 'emd_violations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emd_violations_inspection_id'), 'emd_violations', ['inspection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emd_violations_inspection_id'), table_name='emd_violations')
    op.drop_index(op.f('ix_emd_violations_facility_id'), table_name='emd_violations')
    op.drop_table('emd_violations')
    op.drop_index(op.f('ix_emd_equipment_inspection_id'), table_name='emd_equipment')
    op.drop_index(op.f('ix_emd_equipment_facility_id'), table_name='emd_equipment')
    op.drop_table('emd_equipment')
    op.drop_index(op.f('ix_emd_inspections_inspection_id'), table_name='emd_inspections')
    op.drop_index(op.f('ix_emd_inspections_inspection_date'), table_name='emd_inspections')
    op.drop_index(op.f('ix_emd_inspections_facility_id'), table_name='emd_inspections')
    op.drop_table('emd_inspections')
    op.drop_index(op.f('ix_emd_facilities_organization_id'), table_name='emd_facilities')
    op.drop_index(op.f('ix_emd_facilities_matched_property_id'), table_name='emd_facilities')
    op.drop_index(op.f('ix_emd_facilities_facility_id'), table_name='emd_facilities')
    op.drop_table('emd_facilities')
    # ### end Alembic commands ###
