"""add sanitizer_type to bodies_of_water

Revision ID: 30f09bde76c1
Revises: 8c1a65b5a13d
Create Date: 2026-03-13 09:35:52.426643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f09bde76c1'
down_revision: Union[str, None] = '8c1a65b5a13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodies_of_water', sa.Column('sanitizer_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodies_of_water', 'sanitizer_type')
    # ### end Alembic commands ###
