"""Add role_version to organization_users, for session invalidation on role change

Revision ID: 3255a518bee0
Revises: 81157f268189
Create Date: 2026-03-25 03:12:58.794364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3255a518bee0'
down_revision: Union[str, None] = '81157f268189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_users', sa.Column('role_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_users', 'role_version')
    # ### end Alembic commands ###
