"""add org_id to agent tables and agent config to organizations

Revision ID: 35608be7c143
Revises: 768c0189b4f6
Create Date: 2026-03-24 05:28:48.246288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35608be7c143'
down_revision: Union[str, None] = '768c0189b4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Step 1: Add org_id as NULLABLE ###
    tables = ['agent_action_comments', 'agent_actions', 'agent_messages', 'agent_threads', 'notifications']
    for t in tables:
        op.add_column(t, sa.Column('organization_id', sa.String(length=36), nullable=True))

    # ### Step 2: Add org agent config columns ###
    op.add_column('organizations', sa.Column('agent_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('organizations', sa.Column('agent_from_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('agent_from_name', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('agent_tone_rules', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('agent_signature', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('agent_business_hours_start', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('agent_business_hours_end', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('agent_timezone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('agent_service_area', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('agent_approval_phones', sa.Text(), nullable=True))

    # ### Step 3: Backfill ###
    conn = op.get_bind()
    first_org = conn.execute(sa.text("SELECT id FROM organizations ORDER BY created_at LIMIT 1")).scalar()
    if first_org:
        for t in tables:
            conn.execute(sa.text(f"UPDATE {t} SET organization_id = :oid WHERE organization_id IS NULL"), {"oid": first_org})

        conn.execute(sa.text("""
            UPDATE organizations SET
                agent_from_email = 'contact@sapphire-pools.com',
                agent_from_name = 'Sapphire Pools',
                agent_business_hours_start = 7,
                agent_business_hours_end = 20,
                agent_timezone = 'America/Los_Angeles',
                agent_service_area = 'Elk Grove, CA',
                agent_enabled = TRUE,
                agent_approval_phones = :phones
            WHERE id = :oid
        """), {"oid": first_org, "phones": '[{"phone":"+19168951085","name":"Brian"},{"phone":"+19168966729","name":"Chance"},{"phone":"+19164781260","name":"Kim"}]'})

    # ### Step 4: Set NOT NULL + FK + indexes ###
    for t in tables:
        op.alter_column(t, 'organization_id', nullable=False)
        op.create_index(op.f(f'ix_{t}_organization_id'), t, ['organization_id'], unique=False)
        op.create_foreign_key(None, t, 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'agent_approval_phones')
    op.drop_column('organizations', 'agent_service_area')
    op.drop_column('organizations', 'agent_timezone')
    op.drop_column('organizations', 'agent_business_hours_end')
    op.drop_column('organizations', 'agent_business_hours_start')
    op.drop_column('organizations', 'agent_signature')
    op.drop_column('organizations', 'agent_tone_rules')
    op.drop_column('organizations', 'agent_from_name')
    op.drop_column('organizations', 'agent_from_email')
    op.drop_column('organizations', 'agent_enabled')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_column('notifications', 'organization_id')
    op.drop_constraint(None, 'agent_threads', type_='foreignkey')
    op.drop_index(op.f('ix_agent_threads_organization_id'), table_name='agent_threads')
    op.drop_column('agent_threads', 'organization_id')
    op.drop_constraint(None, 'agent_messages', type_='foreignkey')
    op.drop_index(op.f('ix_agent_messages_organization_id'), table_name='agent_messages')
    op.drop_column('agent_messages', 'organization_id')
    op.drop_constraint(None, 'agent_actions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_actions_organization_id'), table_name='agent_actions')
    op.drop_column('agent_actions', 'organization_id')
    op.drop_constraint(None, 'agent_action_comments', type_='foreignkey')
    op.drop_index(op.f('ix_agent_action_comments_organization_id'), table_name='agent_action_comments')
    op.drop_column('agent_action_comments', 'organization_id')
    # ### end Alembic commands ###
