"""add chemical cost engine tables

Revision ID: 3c069abbfde7
Revises: 239158b298dc
Create Date: 2026-03-16 05:06:29.148632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c069abbfde7'
down_revision: Union[str, None] = '239158b298dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regional_defaults',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_key', sa.String(length=50), nullable=False),
    sa.Column('sanitizer_type', sa.String(length=50), nullable=False),
    sa.Column('sanitizer_usage_oz', sa.Float(), nullable=False),
    sa.Column('acid_usage_oz', sa.Float(), nullable=False),
    sa.Column('sanitizer_price_per_unit', sa.Float(), nullable=True),
    sa.Column('sanitizer_unit', sa.String(length=20), nullable=True),
    sa.Column('acid_price_per_gallon', sa.Float(), nullable=False),
    sa.Column('cya_price_per_lb', sa.Float(), nullable=False),
    sa.Column('salt_price_per_bag', sa.Float(), nullable=False),
    sa.Column('cya_usage_lb_per_month_per_10k', sa.Float(), nullable=False),
    sa.Column('salt_bags_per_year_per_10k', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regional_defaults_region_key'), 'regional_defaults', ['region_key'], unique=False)
    op.create_table('org_chemical_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('liquid_chlorine_per_gal', sa.Float(), nullable=True),
    sa.Column('tabs_per_bucket', sa.Float(), nullable=True),
    sa.Column('cal_hypo_per_lb', sa.Float(), nullable=True),
    sa.Column('dichlor_per_lb', sa.Float(), nullable=True),
    sa.Column('salt_per_bag', sa.Float(), nullable=True),
    sa.Column('acid_per_gal', sa.Float(), nullable=True),
    sa.Column('cya_per_lb', sa.Float(), nullable=True),
    sa.Column('bromine_per_lb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_chemical_prices_organization_id'), 'org_chemical_prices', ['organization_id'], unique=True)
    op.create_table('chemical_cost_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('body_of_water_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sanitizer_cost', sa.Float(), nullable=False),
    sa.Column('acid_cost', sa.Float(), nullable=False),
    sa.Column('cya_cost', sa.Float(), nullable=False),
    sa.Column('salt_cost', sa.Float(), nullable=False),
    sa.Column('total_monthly', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=True),
    sa.Column('adjustments_applied', sa.JSON(), nullable=True),
    sa.Column('last_computed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sanitizer_usage_override_oz', sa.Float(), nullable=True),
    sa.Column('acid_usage_override_oz', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['body_of_water_id'], ['bodies_of_water.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_cost_profiles_body_of_water_id'), 'chemical_cost_profiles', ['body_of_water_id'], unique=True)
    op.create_index(op.f('ix_chemical_cost_profiles_organization_id'), 'chemical_cost_profiles', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemical_cost_profiles_organization_id'), table_name='chemical_cost_profiles')
    op.drop_index(op.f('ix_chemical_cost_profiles_body_of_water_id'), table_name='chemical_cost_profiles')
    op.drop_table('chemical_cost_profiles')
    op.drop_index(op.f('ix_org_chemical_prices_organization_id'), table_name='org_chemical_prices')
    op.drop_table('org_chemical_prices')
    op.drop_index(op.f('ix_regional_defaults_region_key'), table_name='regional_defaults')
    op.drop_table('regional_defaults')
    # ### end Alembic commands ###
