"""phase1_business_tables

Revision ID: 3d3a1af61a79
Revises: edc574f755fb
Create Date: 2026-01-31 11:38:07.583748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3a1af61a79'
down_revision: Union[str, None] = 'edc574f755fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geocode_cache_address_hash'), 'geocode_cache', ['address_hash'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=50), nullable=True),
    sa.Column('billing_zip', sa.String(length=20), nullable=True),
    sa.Column('service_frequency', sa.String(length=50), nullable=True),
    sa.Column('preferred_day', sa.String(length=20), nullable=True),
    sa.Column('billing_frequency', sa.String(length=20), nullable=False),
    sa.Column('monthly_rate', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('difficulty_rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_organization_id'), 'services', ['organization_id'], unique=False)
    op.create_table('techs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('start_address', sa.String(length=255), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('end_address', sa.String(length=255), nullable=True),
    sa.Column('work_start_time', sa.Time(), nullable=True),
    sa.Column('work_end_time', sa.Time(), nullable=True),
    sa.Column('working_days', sa.JSON(), nullable=True),
    sa.Column('max_stops_per_day', sa.Integer(), nullable=False),
    sa.Column('efficiency_factor', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techs_organization_id'), 'techs', ['organization_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geocode_provider', sa.String(length=50), nullable=True),
    sa.Column('pool_type', sa.String(length=50), nullable=True),
    sa.Column('pool_gallons', sa.Integer(), nullable=True),
    sa.Column('pool_surface', sa.String(length=50), nullable=True),
    sa.Column('has_spa', sa.Boolean(), nullable=False),
    sa.Column('has_water_feature', sa.Boolean(), nullable=False),
    sa.Column('pump_type', sa.String(length=100), nullable=True),
    sa.Column('filter_type', sa.String(length=100), nullable=True),
    sa.Column('heater_type', sa.String(length=100), nullable=True),
    sa.Column('chlorinator_type', sa.String(length=100), nullable=True),
    sa.Column('automation_system', sa.String(length=100), nullable=True),
    sa.Column('gate_code', sa.String(length=50), nullable=True),
    sa.Column('access_instructions', sa.Text(), nullable=True),
    sa.Column('dog_on_property', sa.Boolean(), nullable=False),
    sa.Column('estimated_service_minutes', sa.Integer(), nullable=False),
    sa.Column('is_locked_to_day', sa.Boolean(), nullable=False),
    sa.Column('service_day_pattern', sa.String(length=20), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_customer_id'), 'properties', ['customer_id'], unique=False)
    op.create_index(op.f('ix_properties_organization_id'), 'properties', ['organization_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('tech_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('service_day', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('service_performed', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tech_id'], ['techs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_organization_id'), 'visits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visits_property_id'), 'visits', ['property_id'], unique=False)
    op.create_index(op.f('ix_visits_scheduled_date'), 'visits', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_visits_tech_id'), 'visits', ['tech_id'], unique=False)
    op.create_table('chemical_readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('free_chlorine', sa.Float(), nullable=True),
    sa.Column('total_chlorine', sa.Float(), nullable=True),
    sa.Column('combined_chlorine', sa.Float(), nullable=True),
    sa.Column('alkalinity', sa.Float(), nullable=True),
    sa.Column('calcium_hardness', sa.Float(), nullable=True),
    sa.Column('cyanuric_acid', sa.Float(), nullable=True),
    sa.Column('tds', sa.Float(), nullable=True),
    sa.Column('phosphates', sa.Float(), nullable=True),
    sa.Column('salt', sa.Float(), nullable=True),
    sa.Column('water_temp', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_readings_organization_id'), 'chemical_readings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chemical_readings_property_id'), 'chemical_readings', ['property_id'], unique=False)
    op.create_index(op.f('ix_chemical_readings_visit_id'), 'chemical_readings', ['visit_id'], unique=False)
    op.create_table('visit_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_services_service_id'), 'visit_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_visit_services_visit_id'), 'visit_services', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_services_visit_id'), table_name='visit_services')
    op.drop_index(op.f('ix_visit_services_service_id'), table_name='visit_services')
    op.drop_table('visit_services')
    op.drop_index(op.f('ix_chemical_readings_visit_id'), table_name='chemical_readings')
    op.drop_index(op.f('ix_chemical_readings_property_id'), table_name='chemical_readings')
    op.drop_index(op.f('ix_chemical_readings_organization_id'), table_name='chemical_readings')
    op.drop_table('chemical_readings')
    op.drop_index(op.f('ix_visits_tech_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_scheduled_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_property_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_organization_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_properties_organization_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_customer_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_techs_organization_id'), table_name='techs')
    op.drop_table('techs')
    op.drop_index(op.f('ix_services_organization_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_geocode_cache_address_hash'), table_name='geocode_cache')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
