"""add created_by to agent_actions

Revision ID: 425895d2209c
Revises: 0ae300282baf
Create Date: 2026-03-24 04:19:08.534900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425895d2209c'
down_revision: Union[str, None] = '0ae300282baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_actions', sa.Column('created_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_actions', 'created_by')
    # ### end Alembic commands ###
