"""Add internal messaging tables

Revision ID: 4ce80b53793b
Revises: b44f4102895d
Create Date: 2026-03-29 19:08:41.666689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ce80b53793b'
down_revision: Union[str, None] = 'b44f4102895d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('participant_ids', sa.JSON(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=36), nullable=True),
    sa.Column('converted_to_action_id', sa.String(length=36), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_to_action_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_threads_customer_id'), 'internal_threads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_internal_threads_organization_id'), 'internal_threads', ['organization_id'], unique=False)
    op.create_table('internal_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['internal_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_messages_thread_id'), 'internal_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_messages_thread_id'), table_name='internal_messages')
    op.drop_table('internal_messages')
    op.drop_index(op.f('ix_internal_threads_organization_id'), table_name='internal_threads')
    op.drop_index(op.f('ix_internal_threads_customer_id'), table_name='internal_threads')
    op.drop_table('internal_threads')
    # ### end Alembic commands ###
