"""add emd_fa_number and emd_pr_number

Revision ID: 4fc79ce0dc6c
Revises: 78b03ef32bb9
Create Date: 2026-03-22 17:27:36.961810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc79ce0dc6c'
down_revision: Union[str, None] = '78b03ef32bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('emd_fa_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_properties_emd_fa_number'), 'properties', ['emd_fa_number'], unique=False)
    op.add_column('water_features', sa.Column('emd_pr_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_water_features_emd_pr_number'), 'water_features', ['emd_pr_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_features_emd_pr_number'), table_name='water_features')
    op.drop_column('water_features', 'emd_pr_number')
    op.drop_index(op.f('ix_properties_emd_fa_number'), table_name='properties')
    op.drop_column('properties', 'emd_fa_number')
    # ### end Alembic commands ###
