"""add residential dollar adjustment fields to property_difficulty

Revision ID: 587b8e26a186
Revises: f3e541f1c0e4
Create Date: 2026-03-21 09:30:04.514836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587b8e26a186'
down_revision: Union[str, None] = 'f3e541f1c0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_difficulties', sa.Column('res_tree_debris', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('property_difficulties', sa.Column('res_dog', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('property_difficulties', sa.Column('res_customer_demands', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('property_difficulties', sa.Column('res_system_effectiveness', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_difficulties', 'res_system_effectiveness')
    op.drop_column('property_difficulties', 'res_customer_demands')
    op.drop_column('property_difficulties', 'res_dog')
    op.drop_column('property_difficulties', 'res_tree_debris')
    # ### end Alembic commands ###
