"""Visit experience: photos, checklist, route_stop_id, started_at, customer_id

Revision ID: 5a44a0362369
Revises: b79f72a491f8
Create Date: 2026-03-25 19:29:08.879004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a44a0362369'
down_revision: Union[str, None] = 'b79f72a491f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_checklist_items_organization_id'), 'service_checklist_items', ['organization_id'], unique=False)
    op.create_table('visit_checklist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('checklist_item_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['service_checklist_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_checklist_entries_checklist_item_id'), 'visit_checklist_entries', ['checklist_item_id'], unique=False)
    op.create_index(op.f('ix_visit_checklist_entries_visit_id'), 'visit_checklist_entries', ['visit_id'], unique=False)
    op.create_table('visit_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('water_feature_id', sa.String(length=36), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['water_feature_id'], ['water_features.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_photos_organization_id'), 'visit_photos', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visit_photos_visit_id'), 'visit_photos', ['visit_id'], unique=False)
    op.create_index(op.f('ix_visit_photos_water_feature_id'), 'visit_photos', ['water_feature_id'], unique=False)
    op.add_column('visits', sa.Column('route_stop_id', sa.String(length=36), nullable=True))
    op.add_column('visits', sa.Column('customer_id', sa.String(length=36), nullable=True))
    op.add_column('visits', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_visits_customer_id'), 'visits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visits_route_stop_id'), 'visits', ['route_stop_id'], unique=False)
    op.create_foreign_key(None, 'visits', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'visits', 'route_stops', ['route_stop_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_route_stop_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_customer_id'), table_name='visits')
    op.drop_column('visits', 'started_at')
    op.drop_column('visits', 'customer_id')
    op.drop_column('visits', 'route_stop_id')
    op.drop_index(op.f('ix_visit_photos_water_feature_id'), table_name='visit_photos')
    op.drop_index(op.f('ix_visit_photos_visit_id'), table_name='visit_photos')
    op.drop_index(op.f('ix_visit_photos_organization_id'), table_name='visit_photos')
    op.drop_table('visit_photos')
    op.drop_index(op.f('ix_visit_checklist_entries_visit_id'), table_name='visit_checklist_entries')
    op.drop_index(op.f('ix_visit_checklist_entries_checklist_item_id'), table_name='visit_checklist_entries')
    op.drop_table('visit_checklist_entries')
    op.drop_index(op.f('ix_service_checklist_items_organization_id'), table_name='service_checklist_items')
    op.drop_table('service_checklist_items')
    # ### end Alembic commands ###
