"""add_pool_measurements

Revision ID: 5ca1071b5fd5
Revises: 7e86e03dc763
Create Date: 2026-03-12 13:35:59.976970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca1071b5fd5'
down_revision: Union[str, None] = '7e86e03dc763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_measurements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('measured_by', sa.String(length=36), nullable=True),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.Column('width_ft', sa.Float(), nullable=True),
    sa.Column('depth_shallow_ft', sa.Float(), nullable=True),
    sa.Column('depth_deep_ft', sa.Float(), nullable=True),
    sa.Column('depth_avg_ft', sa.Float(), nullable=True),
    sa.Column('calculated_sqft', sa.Float(), nullable=True),
    sa.Column('calculated_gallons', sa.Integer(), nullable=True),
    sa.Column('pool_shape', sa.String(length=50), nullable=True),
    sa.Column('scale_reference', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('photo_paths', sa.JSON(), nullable=True),
    sa.Column('raw_analysis', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_to_property', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['measured_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_measurements_organization_id'), 'pool_measurements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_pool_measurements_property_id'), 'pool_measurements', ['property_id'], unique=False)
    op.add_column('properties', sa.Column('pool_length_ft', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('pool_width_ft', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('pool_depth_shallow', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('pool_depth_deep', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('pool_depth_avg', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('pool_shape', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('pool_volume_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'pool_volume_method')
    op.drop_column('properties', 'pool_shape')
    op.drop_column('properties', 'pool_depth_avg')
    op.drop_column('properties', 'pool_depth_deep')
    op.drop_column('properties', 'pool_depth_shallow')
    op.drop_column('properties', 'pool_width_ft')
    op.drop_column('properties', 'pool_length_ft')
    op.drop_index(op.f('ix_pool_measurements_property_id'), table_name='pool_measurements')
    op.drop_index(op.f('ix_pool_measurements_organization_id'), table_name='pool_measurements')
    op.drop_table('pool_measurements')
    # ### end Alembic commands ###
