"""make_invoice_number_nullable_for_drafts

Revision ID: 625b624e8b18
Revises: 8246d8de3bc7
Create Date: 2026-03-31 12:57:23.147200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625b624e8b18'
down_revision: Union[str, None] = '8246d8de3bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
