"""add is_developer to organization_users

Revision ID: 730d40939df1
Revises: bd23737090e4
Create Date: 2026-03-14 04:54:37.512254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730d40939df1'
down_revision: Union[str, None] = 'bd23737090e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_users', sa.Column('is_developer', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_users', 'is_developer')
    # ### end Alembic commands ###
