"""add agent_threads table and thread_id columns

Revision ID: 768c0189b4f6
Revises: 425895d2209c
Create Date: 2026-03-24 04:56:13.536571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768c0189b4f6'
down_revision: Union[str, None] = '425895d2209c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_key', sa.String(length=500), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('matched_customer_id', sa.String(length=36), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('property_address', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_direction', sa.String(length=10), nullable=False),
    sa.Column('last_snippet', sa.String(length=200), nullable=True),
    sa.Column('has_pending', sa.Boolean(), nullable=False),
    sa.Column('has_open_actions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_threads_thread_key'), 'agent_threads', ['thread_key'], unique=True)
    op.add_column('agent_actions', sa.Column('thread_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_agent_actions_thread_id'), 'agent_actions', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'agent_actions', 'agent_threads', ['thread_id'], ['id'])
    op.add_column('agent_messages', sa.Column('thread_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_agent_messages_thread_id'), 'agent_messages', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'agent_messages', 'agent_threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###

    # --- Data backfill: group existing messages into threads ---
    import uuid, re
    from datetime import datetime, timezone

    conn = op.get_bind()

    def normalize_subject(s):
        if not s:
            return ""
        while True:
            lower = s.lower().strip()
            if lower.startswith("re:"):
                s = s[3:].strip()
            elif lower.startswith("fwd:"):
                s = s[4:].strip()
            elif lower.startswith("fw:"):
                s = s[3:].strip()
            else:
                break
        return s.strip()

    messages = conn.execute(
        sa.text("SELECT id, direction, from_email, to_email, subject, body, category, urgency, status, matched_customer_id, customer_name, property_address, received_at FROM agent_messages ORDER BY received_at ASC")
    ).fetchall()

    threads = {}  # thread_key -> thread_id
    thread_data = {}  # thread_id -> dict of denormalized fields

    for msg in messages:
        contact_email = msg.from_email if msg.direction == "inbound" else (msg.to_email or msg.from_email)
        norm_subj = normalize_subject(msg.subject or "")
        thread_key = f"{norm_subj}|{contact_email}".lower()

        if thread_key not in threads:
            tid = str(uuid.uuid4())
            threads[thread_key] = tid
            now = datetime.now(timezone.utc)
            thread_data[tid] = {
                "id": tid,
                "thread_key": thread_key,
                "contact_email": contact_email,
                "subject": msg.subject,
                "matched_customer_id": msg.matched_customer_id,
                "customer_name": msg.customer_name,
                "property_address": msg.property_address,
                "status": "pending" if msg.status == "pending" else ("handled" if msg.status in ("sent", "auto_sent") else "ignored"),
                "urgency": msg.urgency,
                "category": msg.category if msg.direction == "inbound" else None,
                "message_count": 0,
                "last_message_at": msg.received_at or now,
                "last_direction": msg.direction,
                "last_snippet": (msg.body or "")[:200],
                "has_pending": msg.status == "pending",
                "has_open_actions": False,
                "created_at": msg.received_at or now,
                "updated_at": now,
            }

        tid = threads[thread_key]
        td = thread_data[tid]
        td["message_count"] += 1
        td["last_message_at"] = msg.received_at or td["last_message_at"]
        td["last_direction"] = msg.direction
        td["last_snippet"] = (msg.body or "")[:200]
        if msg.status == "pending":
            td["has_pending"] = True
            td["status"] = "pending"
        elif msg.status in ("sent", "auto_sent") and td["status"] != "pending":
            td["status"] = "handled"
        if msg.direction == "inbound" and msg.category:
            td["category"] = msg.category
        if msg.urgency:
            prio = {"high": 3, "medium": 2, "low": 1}
            if prio.get(msg.urgency, 0) > prio.get(td["urgency"] or "", 0):
                td["urgency"] = msg.urgency
        if msg.matched_customer_id and not td["matched_customer_id"]:
            td["matched_customer_id"] = msg.matched_customer_id
        if msg.customer_name and not td["customer_name"]:
            td["customer_name"] = msg.customer_name

    # Insert threads first (before updating messages)
    for td in thread_data.values():
        conn.execute(sa.text("""
            INSERT INTO agent_threads (id, thread_key, contact_email, subject, matched_customer_id, customer_name, property_address, status, urgency, category, message_count, last_message_at, last_direction, last_snippet, has_pending, has_open_actions, created_at, updated_at)
            VALUES (:id, :thread_key, :contact_email, :subject, :matched_customer_id, :customer_name, :property_address, :status, :urgency, :category, :message_count, :last_message_at, :last_direction, :last_snippet, :has_pending, :has_open_actions, :created_at, :updated_at)
        """), td)

    # Update messages with thread_id
    for msg in messages:
        contact_email = msg.from_email if msg.direction == "inbound" else (msg.to_email or msg.from_email)
        norm_subj = normalize_subject(msg.subject or "")
        thread_key = f"{norm_subj}|{contact_email}".lower()
        tid = threads.get(thread_key)
        if tid:
            conn.execute(sa.text("UPDATE agent_messages SET thread_id = :tid WHERE id = :mid"), {"tid": tid, "mid": msg.id})

    # Update actions with thread_id from their linked message
    conn.execute(sa.text("""
        UPDATE agent_actions SET thread_id = (
            SELECT thread_id FROM agent_messages WHERE agent_messages.id = agent_actions.agent_message_id
        ) WHERE agent_message_id IS NOT NULL
    """))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_messages', type_='foreignkey')
    op.drop_index(op.f('ix_agent_messages_thread_id'), table_name='agent_messages')
    op.drop_column('agent_messages', 'thread_id')
    op.drop_constraint(None, 'agent_actions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_actions_thread_id'), table_name='agent_actions')
    op.drop_column('agent_actions', 'thread_id')
    op.drop_index(op.f('ix_agent_threads_thread_key'), table_name='agent_threads')
    op.drop_table('agent_threads')
    # ### end Alembic commands ###
