"""add scraper_runs table

Revision ID: 78b03ef32bb9
Revises: a5719f79ddff
Create Date: 2026-03-22 16:58:11.112187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b03ef32bb9'
down_revision: Union[str, None] = 'a5719f79ddff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('days_scraped', sa.Integer(), nullable=False),
    sa.Column('inspections_found', sa.Integer(), nullable=False),
    sa.Column('inspections_new', sa.Integer(), nullable=False),
    sa.Column('pdfs_downloaded', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraper_runs')
    # ### end Alembic commands ###
