"""add satellite_analyses table

Revision ID: 7e86e03dc763
Revises: f0fb2db96ebb
Create Date: 2026-03-11 10:14:10.745530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e86e03dc763'
down_revision: Union[str, None] = 'f0fb2db96ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('pool_detected', sa.Boolean(), nullable=False),
    sa.Column('estimated_pool_sqft', sa.Float(), nullable=True),
    sa.Column('pool_contour_points', sa.JSON(), nullable=True),
    sa.Column('pool_confidence', sa.Float(), nullable=False),
    sa.Column('vegetation_pct', sa.Float(), nullable=False),
    sa.Column('canopy_overhang_pct', sa.Float(), nullable=False),
    sa.Column('hardscape_pct', sa.Float(), nullable=False),
    sa.Column('shadow_pct', sa.Float(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_zoom', sa.Integer(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('analysis_version', sa.String(length=20), nullable=False),
    sa.Column('raw_results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_analyses_organization_id'), 'satellite_analyses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_satellite_analyses_property_id'), 'satellite_analyses', ['property_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satellite_analyses_property_id'), table_name='satellite_analyses')
    op.drop_index(op.f('ix_satellite_analyses_organization_id'), table_name='satellite_analyses')
    op.drop_table('satellite_analyses')
    # ### end Alembic commands ###
