"""add document_type to invoices and invoice_id to actions

Revision ID: 7f1cad00a26d
Revises: 30c53d26a091
Create Date: 2026-03-24 17:35:30.103237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1cad00a26d'
down_revision: Union[str, None] = '30c53d26a091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_actions', sa.Column('invoice_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_agent_actions_invoice_id'), 'agent_actions', ['invoice_id'], unique=False)
    op.create_foreign_key(None, 'agent_actions', 'invoices', ['invoice_id'], ['id'])
    op.add_column('invoices', sa.Column('document_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'document_type')
    op.drop_constraint(None, 'agent_actions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_actions_invoice_id'), table_name='agent_actions')
    op.drop_column('agent_actions', 'invoice_id')
    # ### end Alembic commands ###
