"""enrich tech model with operational profile fields

Revision ID: 81157f268189
Revises: e7fd61752b27
Create Date: 2026-03-25 02:49:28.671185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81157f268189'
down_revision: Union[str, None] = 'e7fd61752b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('techs', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('techs', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.add_column('techs', sa.Column('overtime_rate', sa.Float(), nullable=True))
    op.add_column('techs', sa.Column('skills', sa.JSON(), nullable=True))
    op.add_column('techs', sa.Column('certifications', sa.JSON(), nullable=True))
    op.add_column('techs', sa.Column('service_types', sa.JSON(), nullable=True))
    op.add_column('techs', sa.Column('territory_zone', sa.String(length=50), nullable=True))
    op.add_column('techs', sa.Column('vehicle_type', sa.String(length=50), nullable=True))
    op.add_column('techs', sa.Column('vehicle_plate', sa.String(length=20), nullable=True))
    op.add_column('techs', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('techs', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('techs', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_techs_user_id'), 'techs', ['user_id'], unique=True)
    op.create_foreign_key(None, 'techs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'techs', type_='foreignkey')
    op.drop_index(op.f('ix_techs_user_id'), table_name='techs')
    op.drop_column('techs', 'notes')
    op.drop_column('techs', 'hire_date')
    op.drop_column('techs', 'job_title')
    op.drop_column('techs', 'vehicle_plate')
    op.drop_column('techs', 'vehicle_type')
    op.drop_column('techs', 'territory_zone')
    op.drop_column('techs', 'service_types')
    op.drop_column('techs', 'certifications')
    op.drop_column('techs', 'skills')
    op.drop_column('techs', 'overtime_rate')
    op.drop_column('techs', 'hourly_rate')
    op.drop_column('techs', 'user_id')
    # ### end Alembic commands ###
