"""drop_contact_title_make_role_nullable

Revision ID: 8246d8de3bc7
Revises: 78fb11cef021
Create Date: 2026-03-31 12:09:36.205179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8246d8de3bc7'
down_revision: Union[str, None] = '78fb11cef021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_contacts', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.drop_column('customer_contacts', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_contacts', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.alter_column('customer_contacts', 'role',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
