"""Inbox routing rules, thread visibility

Revision ID: 8549932b3737
Revises: c2e98e605937
Create Date: 2026-03-27 06:20:30.113277

"""
from typing import Sequence, Union

import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8549932b3737'
down_revision: Union[str, None] = 'c2e98e605937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_routing_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('address_pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('required_permission', sa.String(length=80), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_routing_rules_organization_id'), 'inbox_routing_rules', ['organization_id'], unique=False)
    op.add_column('agent_messages', sa.Column('delivered_to', sa.String(length=255), nullable=True))
    op.add_column('agent_threads', sa.Column('visibility_permission', sa.String(length=80), nullable=True))
    op.add_column('agent_threads', sa.Column('delivered_to', sa.String(length=255), nullable=True))
    op.add_column('agent_threads', sa.Column('routing_rule_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'agent_threads', 'inbox_routing_rules', ['routing_rule_id'], ['id'])

    # Seed default routing rules for Sapphire Pools (first org with agent_enabled)
    conn = op.get_bind()
    org_row = conn.execute(
        sa.text("SELECT id FROM organizations WHERE agent_enabled = true ORDER BY created_at LIMIT 1")
    ).first()
    if org_row:
        org_id = org_row[0]
        now = datetime.now(timezone.utc)
        conn.execute(
            sa.text(
                "INSERT INTO inbox_routing_rules (id, organization_id, address_pattern, match_type, category, required_permission, priority, is_active, created_at) "
                "VALUES (:id, :org, :addr, :match, :cat, :perm, :pri, true, :ts)"
            ),
            {"id": str(uuid.uuid4()), "org": org_id, "addr": "contact@sapphire-pools.com", "match": "exact", "cat": "service", "perm": None, "pri": 0, "ts": now},
        )
        conn.execute(
            sa.text(
                "INSERT INTO inbox_routing_rules (id, organization_id, address_pattern, match_type, category, required_permission, priority, is_active, created_at) "
                "VALUES (:id, :org, :addr, :match, :cat, :perm, :pri, true, :ts)"
            ),
            {"id": str(uuid.uuid4()), "org": org_id, "addr": "accounting@sapphire-pools.com", "match": "exact", "cat": "billing", "perm": "billing.view", "pri": 10, "ts": now},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_threads', type_='foreignkey')
    op.drop_column('agent_threads', 'routing_rule_id')
    op.drop_column('agent_threads', 'delivered_to')
    op.drop_column('agent_threads', 'visibility_permission')
    op.drop_column('agent_messages', 'delivered_to')
    op.drop_index(op.f('ix_inbox_routing_rules_organization_id'), table_name='inbox_routing_rules')
    op.drop_table('inbox_routing_rules')
    # ### end Alembic commands ###
