"""Add billing_contact_user_id to organizations

Revision ID: 885a91bafc3d
Revises: cbcd44a68a44
Create Date: 2026-03-25 04:17:38.096352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885a91bafc3d'
down_revision: Union[str, None] = 'cbcd44a68a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('billing_contact_user_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'organizations', 'users', ['billing_contact_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'billing_contact_user_id')
    # ### end Alembic commands ###
