"""add shade and debris to bodies_of_water

Revision ID: 8a3b2d7b8d3b
Revises: 339eab0db3fe
Create Date: 2026-03-22 09:16:08.314111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3b2d7b8d3b'
down_revision: Union[str, None] = '339eab0db3fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodies_of_water', sa.Column('shade_exposure', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('bodies_of_water', sa.Column('tree_debris', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodies_of_water', 'tree_debris')
    op.drop_column('bodies_of_water', 'shade_exposure')
    # ### end Alembic commands ###
