"""add_bodies_of_water_table

Revision ID: 8c1a65b5a13d
Revises: 8d12a5655de2
Create Date: 2026-03-13 08:16:36.144129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1a65b5a13d'
down_revision: Union[str, None] = '8d12a5655de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodies_of_water',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('water_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('pool_type', sa.String(length=50), nullable=True),
    sa.Column('pool_gallons', sa.Integer(), nullable=True),
    sa.Column('pool_sqft', sa.Float(), nullable=True),
    sa.Column('pool_surface', sa.String(length=50), nullable=True),
    sa.Column('pool_length_ft', sa.Float(), nullable=True),
    sa.Column('pool_width_ft', sa.Float(), nullable=True),
    sa.Column('pool_depth_shallow', sa.Float(), nullable=True),
    sa.Column('pool_depth_deep', sa.Float(), nullable=True),
    sa.Column('pool_depth_avg', sa.Float(), nullable=True),
    sa.Column('pool_shape', sa.String(length=50), nullable=True),
    sa.Column('pool_volume_method', sa.String(length=20), nullable=True),
    sa.Column('pump_type', sa.String(length=100), nullable=True),
    sa.Column('filter_type', sa.String(length=100), nullable=True),
    sa.Column('heater_type', sa.String(length=100), nullable=True),
    sa.Column('chlorinator_type', sa.String(length=100), nullable=True),
    sa.Column('automation_system', sa.String(length=100), nullable=True),
    sa.Column('estimated_service_minutes', sa.Integer(), nullable=False),
    sa.Column('monthly_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodies_of_water_organization_id'), 'bodies_of_water', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bodies_of_water_property_id'), 'bodies_of_water', ['property_id'], unique=False)
    op.add_column('chemical_readings', sa.Column('body_of_water_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_chemical_readings_body_of_water_id'), 'chemical_readings', ['body_of_water_id'], unique=False)
    op.create_foreign_key(None, 'chemical_readings', 'bodies_of_water', ['body_of_water_id'], ['id'], ondelete='SET NULL')
    op.add_column('pool_measurements', sa.Column('body_of_water_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_pool_measurements_body_of_water_id'), 'pool_measurements', ['body_of_water_id'], unique=False)
    op.create_foreign_key(None, 'pool_measurements', 'bodies_of_water', ['body_of_water_id'], ['id'], ondelete='SET NULL')
    op.add_column('property_difficulties', sa.Column('body_of_water_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_property_difficulties_body_of_water_id'), 'property_difficulties', ['body_of_water_id'], unique=False)
    op.create_foreign_key(None, 'property_difficulties', 'bodies_of_water', ['body_of_water_id'], ['id'], ondelete='SET NULL')
    op.add_column('property_jurisdictions', sa.Column('body_of_water_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_property_jurisdictions_body_of_water_id'), 'property_jurisdictions', ['body_of_water_id'], unique=False)
    op.create_foreign_key(None, 'property_jurisdictions', 'bodies_of_water', ['body_of_water_id'], ['id'], ondelete='SET NULL')

    # --- Data migration: copy property pool data into bodies_of_water ---
    conn = op.get_bind()

    # 1. Create primary BOW for every property, copying pool + equipment fields
    conn.execute(sa.text("""
        INSERT INTO bodies_of_water (
            id, organization_id, property_id, name, water_type, is_primary,
            pool_type, pool_gallons, pool_sqft, pool_surface,
            pool_length_ft, pool_width_ft, pool_depth_shallow, pool_depth_deep, pool_depth_avg,
            pool_shape, pool_volume_method,
            pump_type, filter_type, heater_type, chlorinator_type, automation_system,
            estimated_service_minutes, notes, is_active, created_at, updated_at
        )
        SELECT
            gen_random_uuid()::text, organization_id, id, NULL, 'pool', true,
            pool_type, pool_gallons, pool_sqft, pool_surface,
            pool_length_ft, pool_width_ft, pool_depth_shallow, pool_depth_deep, pool_depth_avg,
            pool_shape, pool_volume_method,
            pump_type, filter_type, heater_type, chlorinator_type, automation_system,
            estimated_service_minutes, NULL, is_active, created_at, updated_at
        FROM properties
    """))

    # 2. Create spa BOW for properties with has_spa=true
    conn.execute(sa.text("""
        INSERT INTO bodies_of_water (
            id, organization_id, property_id, name, water_type, is_primary,
            estimated_service_minutes, is_active, created_at, updated_at
        )
        SELECT
            gen_random_uuid()::text, organization_id, id, 'Spa', 'spa', false,
            10, is_active, created_at, updated_at
        FROM properties
        WHERE has_spa = true
    """))

    # 3. Create water_feature BOW for properties with has_water_feature=true
    conn.execute(sa.text("""
        INSERT INTO bodies_of_water (
            id, organization_id, property_id, name, water_type, is_primary,
            estimated_service_minutes, is_active, created_at, updated_at
        )
        SELECT
            gen_random_uuid()::text, organization_id, id, 'Water Feature', 'water_feature', false,
            5, is_active, created_at, updated_at
        FROM properties
        WHERE has_water_feature = true
    """))

    # 4. Backfill body_of_water_id on child tables to point to primary BOW
    conn.execute(sa.text("""
        UPDATE property_difficulties pd
        SET body_of_water_id = bow.id
        FROM bodies_of_water bow
        WHERE bow.property_id = pd.property_id AND bow.is_primary = true
    """))

    conn.execute(sa.text("""
        UPDATE property_jurisdictions pj
        SET body_of_water_id = bow.id
        FROM bodies_of_water bow
        WHERE bow.property_id = pj.property_id AND bow.is_primary = true
    """))

    conn.execute(sa.text("""
        UPDATE pool_measurements pm
        SET body_of_water_id = bow.id
        FROM bodies_of_water bow
        WHERE bow.property_id = pm.property_id AND bow.is_primary = true
    """))

    conn.execute(sa.text("""
        UPDATE chemical_readings cr
        SET body_of_water_id = bow.id
        FROM bodies_of_water bow
        WHERE bow.property_id = cr.property_id AND bow.is_primary = true
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_jurisdictions', type_='foreignkey')
    op.drop_index(op.f('ix_property_jurisdictions_body_of_water_id'), table_name='property_jurisdictions')
    op.drop_column('property_jurisdictions', 'body_of_water_id')
    op.drop_constraint(None, 'property_difficulties', type_='foreignkey')
    op.drop_index(op.f('ix_property_difficulties_body_of_water_id'), table_name='property_difficulties')
    op.drop_column('property_difficulties', 'body_of_water_id')
    op.drop_constraint(None, 'pool_measurements', type_='foreignkey')
    op.drop_index(op.f('ix_pool_measurements_body_of_water_id'), table_name='pool_measurements')
    op.drop_column('pool_measurements', 'body_of_water_id')
    op.drop_constraint(None, 'chemical_readings', type_='foreignkey')
    op.drop_index(op.f('ix_chemical_readings_body_of_water_id'), table_name='chemical_readings')
    op.drop_column('chemical_readings', 'body_of_water_id')
    op.drop_index(op.f('ix_bodies_of_water_property_id'), table_name='bodies_of_water')
    op.drop_index(op.f('ix_bodies_of_water_organization_id'), table_name='bodies_of_water')
    op.drop_table('bodies_of_water')
    # ### end Alembic commands ###
