"""Add name column to properties

Revision ID: 8d12a5655de2
Revises: 5ca1071b5fd5
Create Date: 2026-03-13 06:18:45.458779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d12a5655de2'
down_revision: Union[str, None] = '5ca1071b5fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'name')
    # ### end Alembic commands ###
