"""add notes to actions and action_comments table

Revision ID: 8ff8b6f49a67
Revises: f403c1a38650
Create Date: 2026-03-23 08:55:57.927038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff8b6f49a67'
down_revision: Union[str, None] = 'f403c1a38650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_action_comments_action_id'), 'agent_action_comments', ['action_id'], unique=False)
    op.add_column('agent_actions', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_actions', 'notes')
    op.drop_index(op.f('ix_agent_action_comments_action_id'), table_name='agent_action_comments')
    op.drop_table('agent_action_comments')
    # ### end Alembic commands ###
