"""add equipment_effectiveness and pool_design_score

Revision ID: 91ba6105c49f
Revises: 18590e8b961d
Create Date: 2026-03-22 09:02:19.488240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ba6105c49f'
down_revision: Union[str, None] = '18590e8b961d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_difficulties', sa.Column('equipment_effectiveness', sa.Float(), nullable=False, server_default='3.0'))
    op.add_column('property_difficulties', sa.Column('pool_design_score', sa.Float(), nullable=False, server_default='3.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_difficulties', 'pool_design_score')
    op.drop_column('property_difficulties', 'equipment_effectiveness')
    # ### end Alembic commands ###
