"""add service_tiers table and service_tier_id on body_of_water

Revision ID: 95c7fa67553d
Revises: b070a619df0c
Create Date: 2026-03-19 07:59:12.259568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c7fa67553d'
down_revision: Union[str, None] = 'b070a619df0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('includes_chems', sa.Boolean(), nullable=False),
    sa.Column('includes_skim', sa.Boolean(), nullable=False),
    sa.Column('includes_baskets', sa.Boolean(), nullable=False),
    sa.Column('includes_vacuum', sa.Boolean(), nullable=False),
    sa.Column('includes_brush', sa.Boolean(), nullable=False),
    sa.Column('includes_equipment_check', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tiers_organization_id'), 'service_tiers', ['organization_id'], unique=False)
    op.add_column('bodies_of_water', sa.Column('service_tier_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'bodies_of_water', 'service_tiers', ['service_tier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bodies_of_water', type_='foreignkey')
    op.drop_column('bodies_of_water', 'service_tier_id')
    op.drop_index(op.f('ix_service_tiers_organization_id'), table_name='service_tiers')
    op.drop_table('service_tiers')
    # ### end Alembic commands ###
