"""add program_identifier to emd_inspections

Revision ID: 96e38028a382
Revises: e4cb9c53436b
Create Date: 2026-03-18 06:37:53.996751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e38028a382'
down_revision: Union[str, None] = 'e4cb9c53436b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emd_inspections', sa.Column('program_identifier', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emd_inspections', 'program_identifier')
    # ### end Alembic commands ###
