"""add permit_id to emd_inspections

Revision ID: a1233ba2e7d0
Revises: 96e38028a382
Create Date: 2026-03-18 06:51:21.004012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1233ba2e7d0'
down_revision: Union[str, None] = '96e38028a382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emd_inspections', sa.Column('permit_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_emd_inspections_permit_id'), 'emd_inspections', ['permit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emd_inspections_permit_id'), table_name='emd_inspections')
    op.drop_column('emd_inspections', 'permit_id')
    # ### end Alembic commands ###
