"""add county to properties

Revision ID: a5719f79ddff
Revises: eb4c4eb7058d
Create Date: 2026-03-22 16:43:50.590000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5719f79ddff'
down_revision: Union[str, None] = 'eb4c4eb7058d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemical_cost_profiles_body_of_water_id'), table_name='chemical_cost_profiles')
    op.create_index(op.f('ix_chemical_cost_profiles_water_feature_id'), 'chemical_cost_profiles', ['water_feature_id'], unique=True)
    op.drop_index(op.f('ix_chemical_readings_body_of_water_id'), table_name='chemical_readings')
    op.create_index(op.f('ix_chemical_readings_water_feature_id'), 'chemical_readings', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_dimension_estimates_body_of_water_id'), table_name='dimension_estimates')
    op.create_index(op.f('ix_dimension_estimates_water_feature_id'), 'dimension_estimates', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_pool_measurements_body_of_water_id'), table_name='pool_measurements')
    op.create_index(op.f('ix_pool_measurements_water_feature_id'), 'pool_measurements', ['water_feature_id'], unique=False)
    op.add_column('properties', sa.Column('county', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_property_difficulties_body_of_water_id'), table_name='property_difficulties')
    op.create_index(op.f('ix_property_difficulties_water_feature_id'), 'property_difficulties', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_property_jurisdictions_body_of_water_id'), table_name='property_jurisdictions')
    op.create_index(op.f('ix_property_jurisdictions_water_feature_id'), 'property_jurisdictions', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_property_photos_body_of_water_id'), table_name='property_photos')
    op.create_index(op.f('ix_property_photos_water_feature_id'), 'property_photos', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_satellite_analyses_body_of_water_id'), table_name='satellite_analyses')
    op.create_index(op.f('ix_satellite_analyses_water_feature_id'), 'satellite_analyses', ['water_feature_id'], unique=True)
    op.drop_index(op.f('ix_bodies_of_water_organization_id'), table_name='water_features')
    op.drop_index(op.f('ix_bodies_of_water_property_id'), table_name='water_features')
    op.create_index(op.f('ix_water_features_organization_id'), 'water_features', ['organization_id'], unique=False)
    op.create_index(op.f('ix_water_features_property_id'), 'water_features', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_features_property_id'), table_name='water_features')
    op.drop_index(op.f('ix_water_features_organization_id'), table_name='water_features')
    op.create_index(op.f('ix_bodies_of_water_property_id'), 'water_features', ['property_id'], unique=False)
    op.create_index(op.f('ix_bodies_of_water_organization_id'), 'water_features', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_satellite_analyses_water_feature_id'), table_name='satellite_analyses')
    op.create_index(op.f('ix_satellite_analyses_body_of_water_id'), 'satellite_analyses', ['water_feature_id'], unique=True)
    op.drop_index(op.f('ix_property_photos_water_feature_id'), table_name='property_photos')
    op.create_index(op.f('ix_property_photos_body_of_water_id'), 'property_photos', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_property_jurisdictions_water_feature_id'), table_name='property_jurisdictions')
    op.create_index(op.f('ix_property_jurisdictions_body_of_water_id'), 'property_jurisdictions', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_property_difficulties_water_feature_id'), table_name='property_difficulties')
    op.create_index(op.f('ix_property_difficulties_body_of_water_id'), 'property_difficulties', ['water_feature_id'], unique=False)
    op.drop_column('properties', 'county')
    op.drop_index(op.f('ix_pool_measurements_water_feature_id'), table_name='pool_measurements')
    op.create_index(op.f('ix_pool_measurements_body_of_water_id'), 'pool_measurements', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_dimension_estimates_water_feature_id'), table_name='dimension_estimates')
    op.create_index(op.f('ix_dimension_estimates_body_of_water_id'), 'dimension_estimates', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_chemical_readings_water_feature_id'), table_name='chemical_readings')
    op.create_index(op.f('ix_chemical_readings_body_of_water_id'), 'chemical_readings', ['water_feature_id'], unique=False)
    op.drop_index(op.f('ix_chemical_cost_profiles_water_feature_id'), table_name='chemical_cost_profiles')
    op.create_index(op.f('ix_chemical_cost_profiles_body_of_water_id'), 'chemical_cost_profiles', ['water_feature_id'], unique=True)
    # ### end Alembic commands ###
