"""add rate allocation tracking to body_of_water

Revision ID: b070a619df0c
Revises: 1323a5b482cb
Create Date: 2026-03-19 07:25:23.672259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b070a619df0c'
down_revision: Union[str, None] = '1323a5b482cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bodies_of_water', sa.Column('rate_allocation_method', sa.String(length=20), nullable=True))
    op.add_column('bodies_of_water', sa.Column('rate_allocated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bodies_of_water', 'rate_allocated_at')
    op.drop_column('bodies_of_water', 'rate_allocation_method')
    # ### end Alembic commands ###
