"""add service_cases table and case_id to actions threads invoices internal_threads

Revision ID: b27c9106539f
Revises: df10c266e289
Create Date: 2026-04-02 04:17:33.241237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b27c9106539f'
down_revision: Union[str, None] = 'df10c266e289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=False),
    sa.Column('open_job_count', sa.Integer(), nullable=False),
    sa.Column('thread_count', sa.Integer(), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('total_invoiced', sa.Float(), nullable=False),
    sa.Column('total_paid', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_index('ix_service_cases_org_customer', 'service_cases', ['organization_id', 'customer_id'], unique=False)
    op.create_index('ix_service_cases_org_status', 'service_cases', ['organization_id', 'status'], unique=False)
    op.create_index('ix_service_cases_org_updated', 'service_cases', ['organization_id', 'updated_at'], unique=False)
    op.add_column('agent_actions', sa.Column('case_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_agent_actions_case_id'), 'agent_actions', ['case_id'], unique=False)
    op.create_foreign_key(None, 'agent_actions', 'service_cases', ['case_id'], ['id'], ondelete='SET NULL')
    op.add_column('agent_threads', sa.Column('case_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_agent_threads_case_id'), 'agent_threads', ['case_id'], unique=False)
    op.create_foreign_key(None, 'agent_threads', 'service_cases', ['case_id'], ['id'], ondelete='SET NULL')
    op.add_column('internal_threads', sa.Column('case_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_internal_threads_case_id'), 'internal_threads', ['case_id'], unique=False)
    op.create_foreign_key(None, 'internal_threads', 'service_cases', ['case_id'], ['id'], ondelete='SET NULL')
    op.add_column('invoices', sa.Column('case_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_invoices_case_id'), 'invoices', ['case_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'service_cases', ['case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_case_id'), table_name='invoices')
    op.drop_column('invoices', 'case_id')
    op.drop_constraint(None, 'internal_threads', type_='foreignkey')
    op.drop_index(op.f('ix_internal_threads_case_id'), table_name='internal_threads')
    op.drop_column('internal_threads', 'case_id')
    op.drop_constraint(None, 'agent_threads', type_='foreignkey')
    op.drop_index(op.f('ix_agent_threads_case_id'), table_name='agent_threads')
    op.drop_column('agent_threads', 'case_id')
    op.drop_constraint(None, 'agent_actions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_actions_case_id'), table_name='agent_actions')
    op.drop_column('agent_actions', 'case_id')
    op.drop_index('ix_service_cases_org_updated', table_name='service_cases')
    op.drop_index('ix_service_cases_org_status', table_name='service_cases')
    op.drop_index('ix_service_cases_org_customer', table_name='service_cases')
    op.drop_table('service_cases')
    # ### end Alembic commands ###
