"""Add feedback_items table

Revision ID: b44f4102895d
Revises: 067d3ab1643b
Create Date: 2026-03-29 11:24:04.649525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b44f4102895d'
down_revision: Union[str, None] = '067d3ab1643b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('screenshot_urls', sa.JSON(), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('browser_info', sa.String(length=500), nullable=True),
    sa.Column('ai_classification', sa.JSON(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_items_organization_id'), 'feedback_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_feedback_items_user_id'), 'feedback_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_items_user_id'), table_name='feedback_items')
    op.drop_index(op.f('ix_feedback_items_organization_id'), table_name='feedback_items')
    op.drop_table('feedback_items')
    # ### end Alembic commands ###
