"""add billing frequency discount fields to org_cost_settings

Revision ID: b5a4523c2def
Revises: 95c7fa67553d
Create Date: 2026-03-19 08:10:01.720680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a4523c2def'
down_revision: Union[str, None] = '95c7fa67553d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_cost_settings', sa.Column('semi_annual_discount_type', sa.String(length=10), nullable=False, server_default='percent'))
    op.add_column('org_cost_settings', sa.Column('semi_annual_discount_value', sa.Float(), nullable=False, server_default='5.0'))
    op.add_column('org_cost_settings', sa.Column('annual_discount_type', sa.String(length=10), nullable=False, server_default='percent'))
    op.add_column('org_cost_settings', sa.Column('annual_discount_value', sa.Float(), nullable=False, server_default='10.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_cost_settings', 'annual_discount_value')
    op.drop_column('org_cost_settings', 'annual_discount_type')
    op.drop_column('org_cost_settings', 'semi_annual_discount_value')
    op.drop_column('org_cost_settings', 'semi_annual_discount_type')
    # ### end Alembic commands ###
