"""Add charge_templates, visit_charges, charge thresholds

Revision ID: b79f72a491f8
Revises: 057dc809476f
Create Date: 2026-03-25 19:10:05.944437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b79f72a491f8'
down_revision: Union[str, None] = '057dc809476f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_templates_organization_id'), 'charge_templates', ['organization_id'], unique=False)
    op.create_table('visit_charges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.String(length=255), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['charge_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_charges_customer_id'), 'visit_charges', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visit_charges_invoice_id'), 'visit_charges', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_visit_charges_organization_id'), 'visit_charges', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visit_charges_property_id'), 'visit_charges', ['property_id'], unique=False)
    op.create_index(op.f('ix_visit_charges_status'), 'visit_charges', ['status'], unique=False)
    op.create_index(op.f('ix_visit_charges_visit_id'), 'visit_charges', ['visit_id'], unique=False)
    op.drop_table('platform_settings')
    op.add_column('org_cost_settings', sa.Column('auto_approve_threshold', sa.Float(), nullable=False, server_default='75.0'))
    op.add_column('org_cost_settings', sa.Column('separate_invoice_threshold', sa.Float(), nullable=False, server_default='200.0'))
    op.add_column('org_cost_settings', sa.Column('require_photo_threshold', sa.Float(), nullable=False, server_default='50.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_cost_settings', 'require_photo_threshold')
    op.drop_column('org_cost_settings', 'separate_invoice_threshold')
    op.drop_column('org_cost_settings', 'auto_approve_threshold')
    op.create_table('platform_settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('platform_settings_pkey'))
    )
    op.drop_index(op.f('ix_visit_charges_visit_id'), table_name='visit_charges')
    op.drop_index(op.f('ix_visit_charges_status'), table_name='visit_charges')
    op.drop_index(op.f('ix_visit_charges_property_id'), table_name='visit_charges')
    op.drop_index(op.f('ix_visit_charges_organization_id'), table_name='visit_charges')
    op.drop_index(op.f('ix_visit_charges_invoice_id'), table_name='visit_charges')
    op.drop_index(op.f('ix_visit_charges_customer_id'), table_name='visit_charges')
    op.drop_table('visit_charges')
    op.drop_index(op.f('ix_charge_templates_organization_id'), table_name='charge_templates')
    op.drop_table('charge_templates')
    # ### end Alembic commands ###
