"""add_normalized_fields_to_equipment_items

Revision ID: c2e98e605937
Revises: d5d481f53120
Create Date: 2026-03-26 06:14:46.608911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2e98e605937'
down_revision: Union[str, None] = 'd5d481f53120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_items', sa.Column('part_number', sa.String(length=100), nullable=True))
    op.add_column('equipment_items', sa.Column('normalized_name', sa.String(length=200), nullable=True))
    op.add_column('equipment_items', sa.Column('horsepower', sa.Float(), nullable=True))
    op.add_column('equipment_items', sa.Column('flow_rate_gpm', sa.Integer(), nullable=True))
    op.add_column('equipment_items', sa.Column('voltage', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_equipment_items_normalized_name'), 'equipment_items', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_items_normalized_name'), table_name='equipment_items')
    op.drop_column('equipment_items', 'voltage')
    op.drop_column('equipment_items', 'flow_rate_gpm')
    op.drop_column('equipment_items', 'horsepower')
    op.drop_column('equipment_items', 'normalized_name')
    op.drop_column('equipment_items', 'part_number')
    # ### end Alembic commands ###
