"""add granular permissions tables

Revision ID: cbcd44a68a44
Revises: 3255a518bee0
Create Date: 2026-03-25 03:32:43.471463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcd44a68a44'
down_revision: Union[str, None] = '3255a518bee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_presets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_presets_slug'), 'permission_presets', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_index(op.f('ix_permissions_slug'), 'permissions', ['slug'], unique=True)
    op.create_table('org_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('based_on_preset_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['based_on_preset_id'], ['permission_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_org_role_slug')
    )
    op.create_index(op.f('ix_org_roles_organization_id'), 'org_roles', ['organization_id'], unique=False)
    op.create_table('preset_permissions',
    sa.Column('preset_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preset_id'], ['permission_presets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('preset_id', 'permission_id')
    )
    op.create_table('org_role_permissions',
    sa.Column('org_role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['org_role_id'], ['org_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_role_id', 'permission_id')
    )
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_user_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_user_id'], ['organization_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_user_id', 'permission_id', name='uq_user_perm_override')
    )
    op.create_index(op.f('ix_user_permission_overrides_org_user_id'), 'user_permission_overrides', ['org_user_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_permission_id'), 'user_permission_overrides', ['permission_id'], unique=False)
    op.add_column('organization_users', sa.Column('org_role_id', sa.String(length=36), nullable=True))
    op.add_column('organization_users', sa.Column('permission_version', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_organization_users_org_role_id'), 'organization_users', ['org_role_id'], unique=False)
    op.create_foreign_key(None, 'organization_users', 'org_roles', ['org_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_users', type_='foreignkey')
    op.drop_index(op.f('ix_organization_users_org_role_id'), table_name='organization_users')
    op.drop_column('organization_users', 'permission_version')
    op.drop_column('organization_users', 'org_role_id')
    op.drop_index(op.f('ix_user_permission_overrides_permission_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_org_user_id'), table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    op.drop_table('org_role_permissions')
    op.drop_table('preset_permissions')
    op.drop_index(op.f('ix_org_roles_organization_id'), table_name='org_roles')
    op.drop_table('org_roles')
    op.drop_index(op.f('ix_permissions_slug'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_permission_presets_slug'), table_name='permission_presets')
    op.drop_table('permission_presets')
    # ### end Alembic commands ###
