"""add_invoice_revisions_table_and_revision_tracking

Revision ID: ce096951c16c
Revises: 163990138c45
Create Date: 2026-03-31 10:51:22.821219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce096951c16c'
down_revision: Union[str, None] = '163990138c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('invoice_number_at_revision', sa.String(length=30), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('revised_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_revisions_invoice_id'), 'invoice_revisions', ['invoice_id'], unique=False)
    op.add_column('invoices', sa.Column('revision_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('revised_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'revised_at')
    op.drop_column('invoices', 'revision_count')
    op.drop_index(op.f('ix_invoice_revisions_invoice_id'), table_name='invoice_revisions')
    op.drop_table('invoice_revisions')
    # ### end Alembic commands ###
