"""Vendor and parts: vendors, parts_catalog, part_purchases, equipment_items, equipment_events

Revision ID: d5d481f53120
Revises: 5a44a0362369
Create Date: 2026-03-26 04:50:57.209459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5d481f53120'
down_revision: Union[str, None] = '5a44a0362369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vendor_provider', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.String(length=500), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('compatible_with', sa.JSON(), nullable=True),
    sa.Column('is_chemical', sa.Boolean(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_provider', 'sku', name='uq_parts_catalog_vendor_sku')
    )
    op.create_index(op.f('ix_parts_catalog_sku'), 'parts_catalog', ['sku'], unique=False)
    op.create_index(op.f('ix_parts_catalog_vendor_provider'), 'parts_catalog', ['vendor_provider'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('portal_url', sa.String(length=500), nullable=True),
    sa.Column('search_url_template', sa.String(length=500), nullable=True),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_organization_id'), 'vendors', ['organization_id'], unique=False)
    op.create_table('equipment_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('water_feature_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('catalog_part_id', sa.String(length=36), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('warranty_expires', sa.Date(), nullable=True),
    sa.Column('expected_lifespan_years', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_part_id'], ['parts_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['equipment_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['water_feature_id'], ['water_features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_items_organization_id'), 'equipment_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_equipment_items_water_feature_id'), 'equipment_items', ['water_feature_id'], unique=False)
    op.create_table('part_purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('catalog_part_id', sa.String(length=36), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('markup_pct', sa.Float(), nullable=True),
    sa.Column('customer_price', sa.Float(), nullable=True),
    sa.Column('visit_charge_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('water_feature_id', sa.String(length=36), nullable=True),
    sa.Column('purchased_by', sa.String(length=36), nullable=False),
    sa.Column('purchased_at', sa.Date(), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_part_id'], ['parts_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['agent_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchased_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_charge_id'], ['visit_charges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['water_feature_id'], ['water_features.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_purchases_job_id'), 'part_purchases', ['job_id'], unique=False)
    op.create_index(op.f('ix_part_purchases_organization_id'), 'part_purchases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_part_purchases_property_id'), 'part_purchases', ['property_id'], unique=False)
    op.create_index(op.f('ix_part_purchases_visit_charge_id'), 'part_purchases', ['visit_charge_id'], unique=False)
    op.create_index(op.f('ix_part_purchases_water_feature_id'), 'part_purchases', ['water_feature_id'], unique=False)
    op.create_table('equipment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('equipment_item_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('part_purchase_id', sa.String(length=36), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['equipment_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_purchase_id'], ['part_purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_events_equipment_item_id'), 'equipment_events', ['equipment_item_id'], unique=False)
    op.create_index(op.f('ix_equipment_events_organization_id'), 'equipment_events', ['organization_id'], unique=False)
    op.add_column('org_cost_settings', sa.Column('default_parts_markup_pct', sa.Float(), nullable=False, server_default='25.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_cost_settings', 'default_parts_markup_pct')
    op.drop_index(op.f('ix_equipment_events_organization_id'), table_name='equipment_events')
    op.drop_index(op.f('ix_equipment_events_equipment_item_id'), table_name='equipment_events')
    op.drop_table('equipment_events')
    op.drop_index(op.f('ix_part_purchases_water_feature_id'), table_name='part_purchases')
    op.drop_index(op.f('ix_part_purchases_visit_charge_id'), table_name='part_purchases')
    op.drop_index(op.f('ix_part_purchases_property_id'), table_name='part_purchases')
    op.drop_index(op.f('ix_part_purchases_organization_id'), table_name='part_purchases')
    op.drop_index(op.f('ix_part_purchases_job_id'), table_name='part_purchases')
    op.drop_table('part_purchases')
    op.drop_index(op.f('ix_equipment_items_water_feature_id'), table_name='equipment_items')
    op.drop_index(op.f('ix_equipment_items_organization_id'), table_name='equipment_items')
    op.drop_table('equipment_items')
    op.drop_index(op.f('ix_vendors_organization_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_parts_catalog_vendor_provider'), table_name='parts_catalog')
    op.drop_index(op.f('ix_parts_catalog_sku'), table_name='parts_catalog')
    op.drop_table('parts_catalog')
    # ### end Alembic commands ###
