"""add recipient_name and recipient_email to estimate_approvals

Revision ID: d6cfc72493b3
Revises: e2e2f726e450
Create Date: 2026-03-30 18:36:44.911124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cfc72493b3'
down_revision: Union[str, None] = 'e2e2f726e450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimate_approvals', sa.Column('recipient_name', sa.String(length=200), nullable=True))
    op.add_column('estimate_approvals', sa.Column('recipient_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimate_approvals', 'recipient_email')
    op.drop_column('estimate_approvals', 'recipient_name')
    # ### end Alembic commands ###
