"""add_thread_reads_table

Revision ID: da35eb55a74d
Revises: 625b624e8b18
Create Date: 2026-03-31 13:58:19.897593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da35eb55a74d'
down_revision: Union[str, None] = '625b624e8b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_reads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'thread_id', name='uq_thread_reads_user_thread')
    )
    op.create_index(op.f('ix_thread_reads_thread_id'), 'thread_reads', ['thread_id'], unique=False)
    op.create_index(op.f('ix_thread_reads_user_id'), 'thread_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thread_reads_user_id'), table_name='thread_reads')
    op.drop_index(op.f('ix_thread_reads_thread_id'), table_name='thread_reads')
    op.drop_table('thread_reads')
    # ### end Alembic commands ###
