"""Add equipment_catalog table and FKs

Revision ID: dbba13977814
Revises: 45f2d8ed66a4
Create Date: 2026-03-28 11:47:59.396300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbba13977814'
down_revision: Union[str, None] = '45f2d8ed66a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_catalog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('specs', sa.JSON(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by_org_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_catalog_canonical_name'), 'equipment_catalog', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_equipment_catalog_equipment_type'), 'equipment_catalog', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_equipment_catalog_manufacturer'), 'equipment_catalog', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_equipment_catalog_model_number'), 'equipment_catalog', ['model_number'], unique=False)
    op.add_column('equipment_items', sa.Column('catalog_equipment_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'equipment_items', 'equipment_catalog', ['catalog_equipment_id'], ['id'], ondelete='SET NULL')
    op.add_column('parts_catalog', sa.Column('for_equipment_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'parts_catalog', 'equipment_catalog', ['for_equipment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts_catalog', type_='foreignkey')
    op.drop_column('parts_catalog', 'for_equipment_id')
    op.drop_constraint(None, 'equipment_items', type_='foreignkey')
    op.drop_column('equipment_items', 'catalog_equipment_id')
    op.drop_index(op.f('ix_equipment_catalog_model_number'), table_name='equipment_catalog')
    op.drop_index(op.f('ix_equipment_catalog_manufacturer'), table_name='equipment_catalog')
    op.drop_index(op.f('ix_equipment_catalog_equipment_type'), table_name='equipment_catalog')
    op.drop_index(op.f('ix_equipment_catalog_canonical_name'), table_name='equipment_catalog')
    op.drop_table('equipment_catalog')
    # ### end Alembic commands ###
