"""add estimate_approvals table and approval fields on invoices

Revision ID: de1b42aa9b2d
Revises: 7f1cad00a26d
Create Date: 2026-03-24 17:46:40.701068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de1b42aa9b2d'
down_revision: Union[str, None] = '7f1cad00a26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('approved_by_type', sa.String(length=20), nullable=False),
    sa.Column('approved_by_name', sa.String(length=200), nullable=False),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('approval_token', sa.String(length=64), nullable=False),
    sa.Column('approval_method', sa.String(length=30), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_token')
    )
    op.create_index(op.f('ix_estimate_approvals_invoice_id'), 'estimate_approvals', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_estimate_approvals_organization_id'), 'estimate_approvals', ['organization_id'], unique=False)
    op.add_column('invoices', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('approved_by', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('approval_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'invoices', 'estimate_approvals', ['approval_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'approval_id')
    op.drop_column('invoices', 'approved_by')
    op.drop_column('invoices', 'approved_at')
    op.drop_index(op.f('ix_estimate_approvals_organization_id'), table_name='estimate_approvals')
    op.drop_index(op.f('ix_estimate_approvals_invoice_id'), table_name='estimate_approvals')
    op.drop_table('estimate_approvals')
    # ### end Alembic commands ###
