"""add user_notified to feedback_items

Revision ID: df10c266e289
Revises: e7088e2b8997
Create Date: 2026-04-01 05:49:44.136972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df10c266e289'
down_revision: Union[str, None] = 'e7088e2b8997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_items', sa.Column('user_notified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_items', 'user_notified')
    # ### end Alembic commands ###
