"""add features, feature_tiers, org_subscriptions tables and org billing columns

Revision ID: e2caa91ea93a
Revises: 19441f30fa8c
Create Date: 2026-03-18 05:03:59.696260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2caa91ea93a'
down_revision: Union[str, None] = '19441f30fa8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('billing_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_slug'), 'features', ['slug'], unique=True)
    op.create_table('feature_tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feature_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('billing_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_id', 'slug', name='uq_feature_tier_slug')
    )
    op.create_index(op.f('ix_feature_tiers_feature_id'), 'feature_tiers', ['feature_id'], unique=False)
    op.create_table('org_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('feature_id', sa.String(length=36), nullable=False),
    sa.Column('feature_tier_id', sa.String(length=36), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_tier_id'], ['feature_tiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'feature_id', 'feature_tier_id', name='uq_org_feature_tier')
    )
    op.create_index(op.f('ix_org_subscriptions_feature_id'), 'org_subscriptions', ['feature_id'], unique=False)
    op.create_index(op.f('ix_org_subscriptions_organization_id'), 'org_subscriptions', ['organization_id'], unique=False)
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'trial_ends_at')
    op.drop_column('organizations', 'billing_email')
    op.drop_column('organizations', 'stripe_customer_id')
    op.drop_index(op.f('ix_org_subscriptions_organization_id'), table_name='org_subscriptions')
    op.drop_index(op.f('ix_org_subscriptions_feature_id'), table_name='org_subscriptions')
    op.drop_table('org_subscriptions')
    op.drop_index(op.f('ix_feature_tiers_feature_id'), table_name='feature_tiers')
    op.drop_table('feature_tiers')
    op.drop_index(op.f('ix_features_slug'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
