"""add emd_lookups table for single facility purchases

Revision ID: e4cb9c53436b
Revises: e2caa91ea93a
Create Date: 2026-03-18 05:30:57.192398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cb9c53436b'
down_revision: Union[str, None] = 'e2caa91ea93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emd_lookups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('facility_id', sa.String(length=36), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=100), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['emd_facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'facility_id', name='uq_org_facility_lookup')
    )
    op.create_index(op.f('ix_emd_lookups_facility_id'), 'emd_lookups', ['facility_id'], unique=False)
    op.create_index(op.f('ix_emd_lookups_organization_id'), 'emd_lookups', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emd_lookups_organization_id'), table_name='emd_lookups')
    op.drop_index(op.f('ix_emd_lookups_facility_id'), table_name='emd_lookups')
    op.drop_table('emd_lookups')
    # ### end Alembic commands ###
