"""add feedback_number to feedback_items

Revision ID: e7088e2b8997
Revises: d6c6065a5826
Create Date: 2026-04-01 05:17:03.539061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7088e2b8997'
down_revision: Union[str, None] = 'd6c6065a5826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_items', sa.Column('feedback_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_feedback_items_feedback_number'), 'feedback_items', ['feedback_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_items_feedback_number'), table_name='feedback_items')
    op.drop_column('feedback_items', 'feedback_number')
    # ### end Alembic commands ###
