"""add tasks to jobs and parent_action_id

Revision ID: e7fd61752b27
Revises: de1b42aa9b2d
Create Date: 2026-03-25 02:20:06.010388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fd61752b27'
down_revision: Union[str, None] = 'de1b42aa9b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_action_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_action_tasks_action_id'), 'agent_action_tasks', ['action_id'], unique=False)
    op.create_index(op.f('ix_agent_action_tasks_organization_id'), 'agent_action_tasks', ['organization_id'], unique=False)
    op.add_column('agent_actions', sa.Column('parent_action_id', sa.String(length=36), nullable=True))
    op.add_column('agent_actions', sa.Column('task_count', sa.Integer(), nullable=True))
    op.add_column('agent_actions', sa.Column('tasks_completed', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_agent_actions_parent_action_id'), 'agent_actions', ['parent_action_id'], unique=False)
    op.create_foreign_key(None, 'agent_actions', 'agent_actions', ['parent_action_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_actions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_actions_parent_action_id'), table_name='agent_actions')
    op.drop_column('agent_actions', 'tasks_completed')
    op.drop_column('agent_actions', 'task_count')
    op.drop_column('agent_actions', 'parent_action_id')
    op.drop_index(op.f('ix_agent_action_tasks_organization_id'), table_name='agent_action_tasks')
    op.drop_index(op.f('ix_agent_action_tasks_action_id'), table_name='agent_action_tasks')
    op.drop_table('agent_action_tasks')
    # ### end Alembic commands ###
