"""phase3b_profitability_tables

Revision ID: f0fb2db96ebb
Revises: b92531d2ea61
Create Date: 2026-03-10 18:50:10.491821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fb2db96ebb'
down_revision: Union[str, None] = 'b92531d2ea61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bather_load_jurisdictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('method_key', sa.Enum('california', 'ispsc', 'mahc', 'texas', 'florida', 'arizona', 'new_york', 'georgia', 'north_carolina', 'illinois', name='jurisdictionmethod'), nullable=False),
    sa.Column('shallow_sqft_per_bather', sa.Float(), nullable=False),
    sa.Column('deep_sqft_per_bather', sa.Float(), nullable=False),
    sa.Column('spa_sqft_per_bather', sa.Float(), nullable=False),
    sa.Column('diving_sqft_per_board', sa.Float(), nullable=False),
    sa.Column('has_deck_bonus', sa.Boolean(), nullable=False),
    sa.Column('deck_sqft_per_bather', sa.Float(), nullable=True),
    sa.Column('has_flow_rate_test', sa.Boolean(), nullable=False),
    sa.Column('flow_gpm_per_bather', sa.Float(), nullable=True),
    sa.Column('has_indoor_multiplier', sa.Boolean(), nullable=False),
    sa.Column('indoor_multiplier', sa.Float(), nullable=True),
    sa.Column('has_limited_use_multiplier', sa.Boolean(), nullable=False),
    sa.Column('limited_use_multiplier', sa.Float(), nullable=True),
    sa.Column('depth_based', sa.Boolean(), nullable=False),
    sa.Column('depth_break_ft', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method_key'),
    sa.UniqueConstraint('name')
    )
    op.create_table('org_cost_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('burdened_labor_rate', sa.Float(), nullable=False),
    sa.Column('vehicle_cost_per_mile', sa.Float(), nullable=False),
    sa.Column('chemical_cost_per_gallon', sa.Float(), nullable=False),
    sa.Column('monthly_overhead', sa.Float(), nullable=False),
    sa.Column('target_margin_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_cost_settings_organization_id'), 'org_cost_settings', ['organization_id'], unique=True)
    op.create_table('property_difficulties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('shallow_sqft', sa.Float(), nullable=True),
    sa.Column('deep_sqft', sa.Float(), nullable=True),
    sa.Column('has_deep_end', sa.Boolean(), nullable=False),
    sa.Column('spa_sqft', sa.Float(), nullable=True),
    sa.Column('diving_board_count', sa.Integer(), nullable=False),
    sa.Column('pump_flow_gpm', sa.Float(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('equipment_age_years', sa.Integer(), nullable=True),
    sa.Column('shade_exposure', sa.Enum('full_sun', 'partial_shade', 'full_shade', name='shadeexposure'), nullable=True),
    sa.Column('tree_debris_level', sa.Enum('none', 'low', 'moderate', 'heavy', name='treedebrislevel'), nullable=True),
    sa.Column('enclosure_type', sa.Enum('open', 'screened', 'indoor', name='enclosuretype'), nullable=True),
    sa.Column('chem_feeder_type', sa.String(length=50), nullable=True),
    sa.Column('access_difficulty_score', sa.Float(), nullable=False),
    sa.Column('customer_demands_score', sa.Float(), nullable=False),
    sa.Column('chemical_demand_score', sa.Float(), nullable=False),
    sa.Column('callback_frequency_score', sa.Float(), nullable=False),
    sa.Column('override_composite', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_difficulties_organization_id'), 'property_difficulties', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_difficulties_property_id'), 'property_difficulties', ['property_id'], unique=True)
    op.create_table('property_jurisdictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['bather_load_jurisdictions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_jurisdictions_jurisdiction_id'), 'property_jurisdictions', ['jurisdiction_id'], unique=False)
    op.create_index(op.f('ix_property_jurisdictions_organization_id'), 'property_jurisdictions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_property_jurisdictions_property_id'), 'property_jurisdictions', ['property_id'], unique=True)
    op.add_column('properties', sa.Column('pool_sqft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'pool_sqft')
    op.drop_index(op.f('ix_property_jurisdictions_property_id'), table_name='property_jurisdictions')
    op.drop_index(op.f('ix_property_jurisdictions_organization_id'), table_name='property_jurisdictions')
    op.drop_index(op.f('ix_property_jurisdictions_jurisdiction_id'), table_name='property_jurisdictions')
    op.drop_table('property_jurisdictions')
    op.drop_index(op.f('ix_property_difficulties_property_id'), table_name='property_difficulties')
    op.drop_index(op.f('ix_property_difficulties_organization_id'), table_name='property_difficulties')
    op.drop_table('property_difficulties')
    op.drop_index(op.f('ix_org_cost_settings_organization_id'), table_name='org_cost_settings')
    op.drop_table('org_cost_settings')
    op.drop_table('bather_load_jurisdictions')
    # ### end Alembic commands ###
