"""add per-type overhead fields to org_cost_settings

Revision ID: f3e541f1c0e4
Revises: 2d880fca8c51
Create Date: 2026-03-19 08:53:15.801584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e541f1c0e4'
down_revision: Union[str, None] = '2d880fca8c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_cost_settings', sa.Column('residential_overhead_per_account', sa.Float(), nullable=False, server_default='10.0'))
    op.add_column('org_cost_settings', sa.Column('commercial_overhead_per_account', sa.Float(), nullable=False, server_default='45.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_cost_settings', 'commercial_overhead_per_account')
    op.drop_column('org_cost_settings', 'residential_overhead_per_account')
    # ### end Alembic commands ###
