"""add branding fields to organizations

Revision ID: f403c1a38650
Revises: a57f0c5c7ac1
Create Date: 2026-03-23 06:05:38.247169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f403c1a38650'
down_revision: Union[str, None] = 'a57f0c5c7ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('primary_color', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('tagline', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'tagline')
    op.drop_column('organizations', 'primary_color')
    # ### end Alembic commands ###
