"""Add first_name, last_name, and display_name to customers

Revision ID: 3123dda5f064
Revises: 21ea4292c605
Create Date: 2025-10-25 07:09:48.570466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3123dda5f064'
down_revision: Union[str, None] = '21ea4292c605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('first_name', sa.String(length=100), nullable=True, comment='First name (for residential)'))
    op.add_column('customers', sa.Column('last_name', sa.String(length=100), nullable=True, comment='Last name (for residential)'))

    # Add display_name as nullable first
    op.add_column('customers', sa.Column('display_name', sa.String(length=200), nullable=True, comment='Display name (auto-generated if not provided)'))

    # Populate display_name from existing name field for all existing records
    op.execute("UPDATE customers SET display_name = name WHERE display_name IS NULL")

    # Now make display_name NOT NULL
    op.alter_column('customers', 'display_name',
               existing_type=sa.String(length=200),
               nullable=False)

    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               comment='Business name (for commercial) or full name (legacy)')
    op.alter_column('customers', 'visit_duration',
               existing_type=sa.INTEGER(),
               comment='Visit duration in minutes',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.drop_index('ix_customers_name', table_name='customers')
    op.create_index(op.f('ix_customers_display_name'), 'customers', ['display_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_display_name'), table_name='customers')
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.alter_column('customers', 'visit_duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Visit duration in minutes',
               existing_nullable=False,
               existing_server_default=sa.text('15'))
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               comment=None,
               existing_comment='Business name (for commercial) or full name (legacy)')
    op.drop_column('customers', 'display_name')
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    # ### end Alembic commands ###
