"""add_visits_and_issues_tables

Revision ID: 6d305a42be80
Revises: 94a842852a05
Create Date: 2025-11-03 07:01:50.103570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d305a42be80'
down_revision: Union[str, None] = '94a842852a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tech_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('service_day', sa.String(length=20), nullable=False),
    sa.Column('actual_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('actual_departure_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('service_performed', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['techs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_customer_id'), 'visits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_visits_organization_id'), 'visits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visits_scheduled_date'), 'visits', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_visits_tech_id'), 'visits', ['tech_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=True),
    sa.Column('reported_by_tech_id', sa.UUID(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_tech_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_tech_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_tech_id'], ['techs.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reported_by_tech_id'], ['techs.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_tech_id'], ['techs.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_assigned_tech_id'), 'issues', ['assigned_tech_id'], unique=False)
    op.create_index(op.f('ix_issues_customer_id'), 'issues', ['customer_id'], unique=False)
    op.create_index(op.f('ix_issues_organization_id'), 'issues', ['organization_id'], unique=False)
    op.create_index(op.f('ix_issues_reported_by_tech_id'), 'issues', ['reported_by_tech_id'], unique=False)
    op.create_index(op.f('ix_issues_visit_id'), 'issues', ['visit_id'], unique=False)
    op.alter_column('tech_routes', 'organization_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Organization this route belongs to',
               existing_nullable=False)
    op.alter_column('tech_routes', 'tech_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Tech this route is for',
               existing_nullable=False)
    op.alter_column('tech_routes', 'service_day',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Day of week (monday, tuesday, etc.)',
               existing_nullable=False)
    op.alter_column('tech_routes', 'route_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Specific date this route is for',
               existing_nullable=False)
    op.alter_column('tech_routes', 'stop_sequence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ordered array of customer IDs',
               existing_nullable=False)
    op.alter_column('tech_routes', 'total_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total route distance in miles',
               existing_nullable=True)
    op.alter_column('tech_routes', 'total_duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total route duration in minutes',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tech_routes', 'total_duration',
               existing_type=sa.INTEGER(),
               comment='Total route duration in minutes',
               existing_nullable=True)
    op.alter_column('tech_routes', 'total_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total route distance in miles',
               existing_nullable=True)
    op.alter_column('tech_routes', 'stop_sequence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered array of customer IDs',
               existing_nullable=False)
    op.alter_column('tech_routes', 'route_date',
               existing_type=sa.DATE(),
               comment='Specific date this route is for',
               existing_nullable=False)
    op.alter_column('tech_routes', 'service_day',
               existing_type=sa.VARCHAR(length=20),
               comment='Day of week (monday, tuesday, etc.)',
               existing_nullable=False)
    op.alter_column('tech_routes', 'tech_id',
               existing_type=sa.UUID(),
               comment='Tech this route is for',
               existing_nullable=False)
    op.alter_column('tech_routes', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this route belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_issues_visit_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_reported_by_tech_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_organization_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_customer_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_assigned_tech_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_visits_tech_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_scheduled_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_organization_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_customer_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
