"""Add status field to customers

Revision ID: 705115ad5228
Revises: 986d4097658d
Create Date: 2025-10-26 05:59:18.485559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705115ad5228'
down_revision: Union[str, None] = '986d4097658d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('status', sa.String(length=20), nullable=False, server_default='active', comment='Customer status: pending, active, inactive'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'status')
    # ### end Alembic commands ###
