"""Add contact and management fields to customers

Revision ID: 986d4097658d
Revises: 3123dda5f064
Create Date: 2025-10-25 07:16:21.565059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986d4097658d'
down_revision: Union[str, None] = '3123dda5f064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(length=255), nullable=True, comment='Primary email address'))
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True, comment='Primary phone number'))
    op.add_column('customers', sa.Column('alt_email', sa.String(length=255), nullable=True, comment='Alternate email address'))
    op.add_column('customers', sa.Column('alt_phone', sa.String(length=20), nullable=True, comment='Alternate phone number'))
    op.add_column('customers', sa.Column('invoice_email', sa.String(length=255), nullable=True, comment='Invoice email (for commercial)'))
    op.add_column('customers', sa.Column('management_company', sa.String(length=200), nullable=True, comment='Management company name (for commercial)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'management_company')
    op.drop_column('customers', 'invoice_email')
    op.drop_column('customers', 'alt_phone')
    op.drop_column('customers', 'alt_email')
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
