"""Add color to drivers and assigned_driver_id to customers

Revision ID: af195a4682fd
Revises: eb0a43468a07
Create Date: 2025-10-24 04:28:38.368585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af195a4682fd'
down_revision: Union[str, None] = 'eb0a43468a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('assigned_driver_id', sa.UUID(), nullable=True, comment='Driver assigned to service this customer'))
    op.create_foreign_key(None, 'customers', 'drivers', ['assigned_driver_id'], ['id'])
    op.add_column('drivers', sa.Column('color', sa.String(length=7), nullable=False, server_default='#3498db', comment='Hex color code for route visualization'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'color')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'assigned_driver_id')
    # ### end Alembic commands ###
