"""Add service schedule fields to customers

Revision ID: eb0a43468a07
Revises: 8ca7afdd9df6
Create Date: 2025-10-23 19:33:59.090149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0a43468a07'
down_revision: Union[str, None] = '8ca7afdd9df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add service_days_per_week as nullable first
    op.add_column('customers', sa.Column('service_days_per_week', sa.Integer(), nullable=True, comment='Number of service days per week (1, 2, or 3)'))

    # Update existing records to default value of 1
    op.execute("UPDATE customers SET service_days_per_week = 1 WHERE service_days_per_week IS NULL")

    # Now make it NOT NULL
    op.alter_column('customers', 'service_days_per_week', nullable=False)

    op.add_column('customers', sa.Column('service_schedule', sa.String(length=50), nullable=True, comment="Current schedule pattern (e.g., 'Mo/Th', 'Mo/We/Fr'). NULL for single-day schedules."))
    op.alter_column('customers', 'service_day',
               existing_type=sa.VARCHAR(length=20),
               comment='Primary service day: monday, tuesday, wednesday, thursday, friday, saturday, sunday',
               existing_comment='monday, tuesday, wednesday, thursday, friday, saturday, sunday',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'service_day',
               existing_type=sa.VARCHAR(length=20),
               comment='monday, tuesday, wednesday, thursday, friday, saturday, sunday',
               existing_comment='Primary service day: monday, tuesday, wednesday, thursday, friday, saturday, sunday',
               existing_nullable=False)
    op.drop_column('customers', 'service_schedule')
    op.drop_column('customers', 'service_days_per_week')
    # ### end Alembic commands ###
