"""Add temp tech assignments table

Revision ID: f85398694f75
Revises: 4019b4ba8ca1
Create Date: 2025-11-02 05:29:31.815405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f85398694f75'
down_revision: Union[str, None] = '4019b4ba8ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization this driver belongs to'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False, comment='Hex color code for route visualization'),
    sa.Column('start_location_address', sa.String(length=500), nullable=False),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('end_location_address', sa.String(length=500), nullable=False),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('working_hours_start', sa.Time(), nullable=False, comment='Start of workday'),
    sa.Column('working_hours_end', sa.Time(), nullable=False, comment='End of workday'),
    sa.Column('max_customers_per_day', sa.Integer(), nullable=False, comment='Maximum number of customers this driver can service in one day'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this driver is currently active/available'),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_name'), 'drivers', ['name'], unique=False)
    op.create_index(op.f('ix_drivers_organization_id'), 'drivers', ['organization_id'], unique=False)
    op.create_table('temp_tech_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('tech_id', sa.UUID(), nullable=False),
    sa.Column('service_day', sa.String(length=20), nullable=False),
    sa.Column('assignment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['techs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temp_assignments_customer_day', 'temp_tech_assignments', ['customer_id', 'service_day', 'assignment_date'], unique=False)
    op.create_index('ix_temp_assignments_org_date', 'temp_tech_assignments', ['organization_id', 'assignment_date'], unique=False)
    op.drop_index('idx_geocoding_cache_hash', table_name='geocoding_cache')
    op.drop_index('idx_geocoding_cache_last_used', table_name='geocoding_cache')
    op.drop_index('idx_geocoding_cache_provider', table_name='geocoding_cache')
    op.drop_table('geocoding_cache')
    op.drop_table('usage_tracking')
    op.drop_table('service_plans')
    op.drop_table('customer_service_agreements')
    op.drop_table('organization_subscriptions')
    op.drop_table('payment_methods')
    op.alter_column('customers', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this customer belongs to',
               existing_nullable=False)
    op.alter_column('customers', 'geocoding_provider',
               existing_type=sa.VARCHAR(length=50),
               comment='Provider used for geocoding',
               existing_nullable=True)
    op.alter_column('customers', 'geocoded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='When geocoding occurred',
               existing_nullable=True)
    op.alter_column('customers', 'assigned_tech_id',
               existing_type=sa.UUID(),
               comment='Tech assigned to service this customer',
               existing_comment='Driver assigned to service this customer',
               existing_nullable=True)
    op.drop_index('idx_customers_geocoding_provider', table_name='customers')
    op.drop_index('idx_customers_org', table_name='customers')
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.drop_constraint('fk_customers_geocoded_by', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'users', ['geocoded_by'], ['id'])
    op.alter_column('organization_users', 'invitation_accepted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('organization_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_org_users_invitation_token', table_name='organization_users')
    op.drop_index('idx_org_users_org', table_name='organization_users')
    op.drop_index('idx_org_users_role', table_name='organization_users')
    op.drop_index('idx_org_users_user', table_name='organization_users')
    op.create_index(op.f('ix_organization_users_id'), 'organization_users', ['id'], unique=False)
    op.create_index(op.f('ix_organization_users_invitation_token'), 'organization_users', ['invitation_token'], unique=False)
    op.create_index(op.f('ix_organization_users_organization_id'), 'organization_users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_users_role'), 'organization_users', ['role'], unique=False)
    op.create_index(op.f('ix_organization_users_user_id'), 'organization_users', ['user_id'], unique=False)
    op.alter_column('organizations', 'billing_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_orgs_slug', table_name='organizations')
    op.drop_index('idx_orgs_stripe_customer', table_name='organizations')
    op.drop_index('idx_orgs_subdomain', table_name='organizations')
    op.drop_index('idx_orgs_subscription_status', table_name='organizations')
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_index('idx_route_stops_org', table_name='route_stops')
    op.drop_constraint('fk_route_stops_organization', 'route_stops', type_='foreignkey')
    op.drop_column('route_stops', 'organization_id')
    op.alter_column('routes', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this route belongs to',
               existing_nullable=False)
    op.drop_index('idx_routes_org', table_name='routes')
    op.create_index(op.f('ix_routes_organization_id'), 'routes', ['organization_id'], unique=False)
    op.alter_column('techs', 'organization_id',
               existing_type=sa.UUID(),
               comment='Organization this tech belongs to',
               existing_nullable=False)
    op.alter_column('techs', 'geocoding_provider',
               existing_type=sa.VARCHAR(length=50),
               comment='Provider used for geocoding (google, mapbox, etc.)',
               existing_nullable=True)
    op.alter_column('techs', 'geocoded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When geocoding was last performed',
               existing_nullable=True)
    op.alter_column('techs', 'max_customers_per_day',
               existing_type=sa.INTEGER(),
               comment='Maximum number of customers this tech can service in one day',
               existing_comment='Maximum number of customers this driver can service in one day',
               existing_nullable=False)
    op.alter_column('techs', 'efficiency_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Efficiency multiplier for route optimization (e.g., 1.5 = 50% more efficient)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('techs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this tech is currently active/available',
               existing_comment='Whether this driver is currently active/available',
               existing_nullable=False)
    op.drop_index('idx_techs_geocoding_provider', table_name='techs')
    op.drop_index('idx_techs_org', table_name='techs')
    op.create_index(op.f('ix_techs_geocoding_provider'), 'techs', ['geocoding_provider'], unique=False)
    op.create_index(op.f('ix_techs_organization_id'), 'techs', ['organization_id'], unique=False)
    op.alter_column('users', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'password_reset_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'last_login_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_index('idx_users_email_verification_token', table_name='users')
    op.drop_index('idx_users_password_reset_token', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_password_reset_token', 'users', ['password_reset_token'], unique=False)
    op.create_index('idx_users_email_verification_token', 'users', ['email_verification_token'], unique=False)
    op.create_index('idx_users_email_lower', 'users', [sa.text('lower(email::text)')], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'password_reset_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'email_verified_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_techs_organization_id'), table_name='techs')
    op.drop_index(op.f('ix_techs_geocoding_provider'), table_name='techs')
    op.create_index('idx_techs_org', 'techs', ['organization_id'], unique=False)
    op.create_index('idx_techs_geocoding_provider', 'techs', ['geocoding_provider'], unique=False)
    op.alter_column('techs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Whether this driver is currently active/available',
               existing_comment='Whether this tech is currently active/available',
               existing_nullable=False)
    op.alter_column('techs', 'efficiency_multiplier',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Efficiency multiplier for route optimization (e.g., 1.5 = 50% more efficient)',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('techs', 'max_customers_per_day',
               existing_type=sa.INTEGER(),
               comment='Maximum number of customers this driver can service in one day',
               existing_comment='Maximum number of customers this tech can service in one day',
               existing_nullable=False)
    op.alter_column('techs', 'geocoded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When geocoding was last performed',
               existing_nullable=True)
    op.alter_column('techs', 'geocoding_provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Provider used for geocoding (google, mapbox, etc.)',
               existing_nullable=True)
    op.alter_column('techs', 'organization_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Organization this tech belongs to',
               existing_nullable=False)
    op.drop_index(op.f('ix_routes_organization_id'), table_name='routes')
    op.create_index('idx_routes_org', 'routes', ['organization_id'], unique=False)
    op.alter_column('routes', 'organization_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Organization this route belongs to',
               existing_nullable=False)
    op.add_column('route_stops', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_route_stops_organization', 'route_stops', 'organizations', ['organization_id'], ['id'])
    op.create_index('idx_route_stops_org', 'route_stops', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.create_index('idx_orgs_subscription_status', 'organizations', ['subscription_status'], unique=False)
    op.create_index('idx_orgs_subdomain', 'organizations', ['subdomain'], unique=False)
    op.create_index('idx_orgs_stripe_customer', 'organizations', ['stripe_customer_id'], unique=False)
    op.create_index('idx_orgs_slug', 'organizations', ['slug'], unique=False)
    op.alter_column('organizations', 'billing_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_organization_users_user_id'), table_name='organization_users')
    op.drop_index(op.f('ix_organization_users_role'), table_name='organization_users')
    op.drop_index(op.f('ix_organization_users_organization_id'), table_name='organization_users')
    op.drop_index(op.f('ix_organization_users_invitation_token'), table_name='organization_users')
    op.drop_index(op.f('ix_organization_users_id'), table_name='organization_users')
    op.create_index('idx_org_users_user', 'organization_users', ['user_id'], unique=False)
    op.create_index('idx_org_users_role', 'organization_users', ['role'], unique=False)
    op.create_index('idx_org_users_org', 'organization_users', ['organization_id'], unique=False)
    op.create_index('idx_org_users_invitation_token', 'organization_users', ['invitation_token'], unique=False)
    op.alter_column('organization_users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_users', 'invitation_accepted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('fk_customers_geocoded_by', 'customers', 'users', ['geocoded_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.create_index('idx_customers_org', 'customers', ['organization_id'], unique=False)
    op.create_index('idx_customers_geocoding_provider', 'customers', ['geocoding_provider'], unique=False)
    op.alter_column('customers', 'assigned_tech_id',
               existing_type=sa.UUID(),
               comment='Driver assigned to service this customer',
               existing_comment='Tech assigned to service this customer',
               existing_nullable=True)
    op.alter_column('customers', 'geocoded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When geocoding occurred',
               existing_nullable=True)
    op.alter_column('customers', 'geocoding_provider',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Provider used for geocoding',
               existing_nullable=True)
    op.alter_column('customers', 'organization_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Organization this customer belongs to',
               existing_nullable=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='payment_methods_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_methods_pkey')
    )
    op.create_table('organization_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='organization_subscriptions_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='organization_subscriptions_pkey')
    )
    op.create_table('customer_service_agreements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customer_service_agreements_pkey')
    )
    op.create_table('service_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='service_plans_pkey')
    )
    op.create_table('usage_tracking',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='usage_tracking_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usage_tracking_pkey')
    )
    op.create_table('geocoding_cache',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('address_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('normalized_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('formatted_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hit_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='geocoding_cache_pkey'),
    sa.UniqueConstraint('address_hash', name='geocoding_cache_address_hash_key')
    )
    op.create_index('idx_geocoding_cache_provider', 'geocoding_cache', ['provider'], unique=False)
    op.create_index('idx_geocoding_cache_last_used', 'geocoding_cache', ['last_used_at'], unique=False)
    op.create_index('idx_geocoding_cache_hash', 'geocoding_cache', ['address_hash'], unique=False)
    op.drop_index('ix_temp_assignments_org_date', table_name='temp_tech_assignments')
    op.drop_index('ix_temp_assignments_customer_day', table_name='temp_tech_assignments')
    op.drop_table('temp_tech_assignments')
    op.drop_index(op.f('ix_drivers_organization_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
